SELECT DISTINCT R.CODICEARTICOLO, A.DESCRIZIONE, R.UNITADIMISURA
,CAST('TUTTI' AS VARCHAR(20)) AS SOTTOCANTIERE1
,CAST('TUTTI' AS VARCHAR(20)) AS SOTTOCANTIERE2
,CAST('TUTTI' AS VARCHAR(20)) AS SOTTOCANTIERE3
,CAST('TUTTI' AS VARCHAR(20)) AS SOTTOCANTIERE4
,CAST('TUTTI' AS VARCHAR(20)) AS SOTTOCANTIERE5
,CAST('TUTTI' AS VARCHAR(20)) AS SOTTOCANTIERE6
,CAST((SELECT SUM(R2.QTA) FROM RIGHIPRV R2
      INNER JOIN PRVORDCL T2 ON (R2.TIPODOCUMENTO=T2.TIPODOCUMENTO AND R2.REGISTRO=T2.REGISTRO AND R2.NUMORDPREV=T2.NUMORDPREV AND R2.DATADOCUMENTO=T2.DATADOCUMENTO)
      WHERE R2.CODICEARTICOLO=R.CODICEARTICOLO
      AND ((R2.Pratica = '83')AND(R2.DataPratica1='10/03/2005'))
      AND R2.SEGNOOPERAZIONECANTIERE='C'
      ) AS NUMERIC(11,4)) AS QTACOMMESSA
,CAST((SELECT SUM(R2.QTA) FROM RIGHIPRV R2
      INNER JOIN PRVORDCL T2 ON (R2.TIPODOCUMENTO=T2.TIPODOCUMENTO AND R2.REGISTRO=T2.REGISTRO AND R2.NUMORDPREV=T2.NUMORDPREV AND R2.DATADOCUMENTO=T2.DATADOCUMENTO)
      WHERE R2.CODICEARTICOLO=R.CODICEARTICOLO
      AND ((R2.Pratica = '83')AND(R2.DataPratica1='10/03/2005'))
      AND R2.SEGNOOPERAZIONECANTIERE='+'
      ) AS NUMERIC(11,4)) AS QTACARICO
,CAST((SELECT SUM(R2.QTA) FROM RIGHIPRV R2
      INNER JOIN PRVORDCL T2 ON (R2.TIPODOCUMENTO=T2.TIPODOCUMENTO AND R2.REGISTRO=T2.REGISTRO AND R2.NUMORDPREV=T2.NUMORDPREV AND R2.DATADOCUMENTO=T2.DATADOCUMENTO)
      WHERE R2.CODICEARTICOLO=R.CODICEARTICOLO
      AND ((R2.Pratica = '83')AND(R2.DataPratica1='10/03/2005'))
      AND R2.SEGNOOPERAZIONECANTIERE='-'
      ) AS NUMERIC(11,4)) AS QTASCARICO
,CAST((SELECT SUM(R2.QTA) FROM RIGHIPRV R2
      INNER JOIN PRVORDCL T2 ON (R2.TIPODOCUMENTO=T2.TIPODOCUMENTO AND R2.REGISTRO=T2.REGISTRO AND R2.NUMORDPREV=T2.NUMORDPREV AND R2.DATADOCUMENTO=T2.DATADOCUMENTO)
      WHERE R2.CODICEARTICOLO=R.CODICEARTICOLO
      AND ((R2.Pratica = '83')AND(R2.DataPratica1='10/03/2005'))
      AND R2.SEGNOOPERAZIONECANTIERE='M'
      ) AS NUMERIC(11,4)) AS QTAMONTATA
,CAST((SELECT SUM(R2.IMPORTORIGO) FROM RIGHIPRV R2
      INNER JOIN PRVORDCL T2 ON (R2.TIPODOCUMENTO=T2.TIPODOCUMENTO AND R2.REGISTRO=T2.REGISTRO AND R2.NUMORDPREV=T2.NUMORDPREV AND R2.DATADOCUMENTO=T2.DATADOCUMENTO)
      WHERE R2.CODICEARTICOLO=R.CODICEARTICOLO
      AND ((R2.Pratica = '83')AND(R2.DataPratica1='10/03/2005'))
      AND R2.SEGNOOPERAZIONECANTIERE='+'
      ) AS NUMERIC(11,4)) AS IMPORTOCARICO
,CAST((SELECT SUM(R2.IMPORTORIGO) FROM RIGHIPRV R2
      INNER JOIN PRVORDCL T2 ON (R2.TIPODOCUMENTO=T2.TIPODOCUMENTO AND R2.REGISTRO=T2.REGISTRO AND R2.NUMORDPREV=T2.NUMORDPREV AND R2.DATADOCUMENTO=T2.DATADOCUMENTO)
      WHERE R2.CODICEARTICOLO=R.CODICEARTICOLO
      AND ((R2.Pratica = '83')AND(R2.DataPratica1='10/03/2005'))
      AND R2.SEGNOOPERAZIONECANTIERE='-'
      ) AS NUMERIC(11,4)) AS IMPORTOSCARICO
,CAST(NULL AS NUMERIC(11,4)) AS IMPORTOCARICOIVACOMP
,CAST(NULL AS NUMERIC(11,4)) AS IMPORTOSCARICOIVACOMP
,CAST(NULL AS NUMERIC(11,4)) AS IMPORTOACQUISTOCARICO
,CAST(NULL AS NUMERIC(11,4)) AS IMPORTOACQUISTOSCARICO
FROM RIGHIPRV R
LEFT JOIN ARTICOLI A ON (A.CODICEARTICOLO=R.CODICEARTICOLO)
INNER JOIN PRVORDCL T ON (R.TIPODOCUMENTO=T.TIPODOCUMENTO AND R.REGISTRO=T.REGISTRO AND R.NUMORDPREV=T.NUMORDPREV AND R.DATADOCUMENTO=T.DATADOCUMENTO)
WHERE R.SEGNOOPERAZIONECANTIERE<>'=' AND R.SEGNOOPERAZIONECANTIERE IS NOT NULL
AND ((R.Pratica = '83')AND(R.DataPratica1='10/03/2005'))
AND (
 R.SEGNOOPERAZIONECANTIERE = 'C' OR
 R.SEGNOOPERAZIONECANTIERE = '+' OR
 R.SEGNOOPERAZIONECANTIERE = '-' OR
 R.SEGNOOPERAZIONECANTIERE = 'M' OR
 R.SEGNOOPERAZIONECANTIERE = '=' OR R.SEGNOOPERAZIONECANTIERE IS NULL OR R.SEGNOOPERAZIONECANTIERE = ''
)
