unit QRAll4690Pag3;

interface

uses Windows, SysUtils, Messages, Classes, Graphics, Controls,
  ExtCtrls, Forms, QuickRpt, QRCtrls, DB;

const
  MATERIALI_MAX_RIGHE = 32;

type
  TAll4690Pag3QR = class(TQuickRep)
    QRBandSchema: TQRBand;
    QRLabel25: TQRLabel;
    QRShape3: TQRShape;
    QRShape10: TQRShape;
    QRLabel53: TQRLabel;
    CheckUNI: TQRLabel;
    QRShape4: TQRShape;
    QRLabel26: TQRLabel;
    QRShape5: TQRShape;
    QRLabel27: TQRLabel;
    QRShape6: TQRShape;
    QRLabel28: TQRLabel;
    QRShape7: TQRShape;
    QRLabel29: TQRLabel;
    QRShape8: TQRShape;
    QRLabel30: TQRLabel;
    QRShape9: TQRShape;
    QRLabel31: TQRLabel;
    QRShape11: TQRShape;
    QRLabel32: TQRLabel;
    QRShape12: TQRShape;
    QRLabel33: TQRLabel;
    QRShape13: TQRShape;
    QRLabel34: TQRLabel;
    QRShape15: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRShape20: TQRShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape23: TQRShape;
    LabApp_0_0: TQRLabel;
    LabApp_0_1: TQRLabel;
    LabApp_0_2: TQRLabel;
    LabApp_0_4: TQRLabel;
    LabApp_0_5: TQRLabel;
    LabApp_0_6: TQRLabel;
    LabApp_0_7: TQRLabel;
    LabApp_0_3: TQRLabel;
    LabApp_0_8: TQRLabel;
    QRShape25: TQRShape;
    QRShape26: TQRShape;
    QRShape27: TQRShape;
    QRShape28: TQRShape;
    QRShape29: TQRShape;
    QRShape30: TQRShape;
    QRShape31: TQRShape;
    QRShape32: TQRShape;
    QRShape33: TQRShape;
    LabApp_1_0: TQRLabel;
    LabApp_1_1: TQRLabel;
    LabApp_1_2: TQRLabel;
    LabApp_1_4: TQRLabel;
    LabApp_1_5: TQRLabel;
    LabApp_1_6: TQRLabel;
    LabApp_1_7: TQRLabel;
    LabApp_1_3: TQRLabel;
    LabApp_1_8: TQRLabel;
    QRShape35: TQRShape;
    QRShape36: TQRShape;
    QRShape37: TQRShape;
    QRShape38: TQRShape;
    QRShape39: TQRShape;
    QRShape40: TQRShape;
    QRShape41: TQRShape;
    QRShape42: TQRShape;
    QRShape43: TQRShape;
    LabApp_2_0: TQRLabel;
    LabApp_2_1: TQRLabel;
    LabApp_2_2: TQRLabel;
    LabApp_2_4: TQRLabel;
    LabApp_2_5: TQRLabel;
    LabApp_2_6: TQRLabel;
    LabApp_2_7: TQRLabel;
    LabApp_2_3: TQRLabel;
    LabApp_2_8: TQRLabel;
    QRShape45: TQRShape;
    QRShape46: TQRShape;
    QRShape47: TQRShape;
    QRShape48: TQRShape;
    QRShape49: TQRShape;
    QRShape50: TQRShape;
    QRShape51: TQRShape;
    QRShape52: TQRShape;
    QRShape53: TQRShape;
    LabApp_3_0: TQRLabel;
    LabApp_3_1: TQRLabel;
    LabApp_3_2: TQRLabel;
    LabApp_3_4: TQRLabel;
    LabApp_3_5: TQRLabel;
    LabApp_3_6: TQRLabel;
    LabApp_3_7: TQRLabel;
    LabApp_3_3: TQRLabel;
    LabApp_3_8: TQRLabel;
    QRShape55: TQRShape;
    QRShape56: TQRShape;
    QRShape57: TQRShape;
    QRShape58: TQRShape;
    QRShape59: TQRShape;
    QRShape60: TQRShape;
    QRShape61: TQRShape;
    QRShape62: TQRShape;
    QRShape63: TQRShape;
    LabApp_4_0: TQRLabel;
    LabApp_4_1: TQRLabel;
    LabApp_4_2: TQRLabel;
    LabApp_4_4: TQRLabel;
    LabApp_4_5: TQRLabel;
    LabApp_4_6: TQRLabel;
    LabApp_4_7: TQRLabel;
    LabApp_4_3: TQRLabel;
    LabApp_4_8: TQRLabel;
    QRShape65: TQRShape;
    QRShape66: TQRShape;
    QRShape67: TQRShape;
    QRShape68: TQRShape;
    QRShape69: TQRShape;
    QRShape70: TQRShape;
    QRShape71: TQRShape;
    QRShape72: TQRShape;
    QRShape73: TQRShape;
    LabApp_5_0: TQRLabel;
    LabApp_5_1: TQRLabel;
    LabApp_5_2: TQRLabel;
    LabApp_5_4: TQRLabel;
    LabApp_5_5: TQRLabel;
    LabApp_5_6: TQRLabel;
    LabApp_5_7: TQRLabel;
    LabApp_5_3: TQRLabel;
    LabApp_5_8: TQRLabel;
    QRShape75: TQRShape;
    QRShape76: TQRShape;
    QRShape77: TQRShape;
    QRShape78: TQRShape;
    QRShape79: TQRShape;
    QRShape80: TQRShape;
    QRShape81: TQRShape;
    QRShape82: TQRShape;
    QRShape83: TQRShape;
    LabApp_6_0: TQRLabel;
    LabApp_6_1: TQRLabel;
    LabApp_6_2: TQRLabel;
    LabApp_6_4: TQRLabel;
    LabApp_6_5: TQRLabel;
    LabApp_6_6: TQRLabel;
    LabApp_6_7: TQRLabel;
    LabApp_6_3: TQRLabel;
    LabApp_6_8: TQRLabel;
    QRShape85: TQRShape;
    QRShape86: TQRShape;
    QRShape87: TQRShape;
    QRShape88: TQRShape;
    QRShape89: TQRShape;
    QRShape90: TQRShape;
    QRShape91: TQRShape;
    QRShape92: TQRShape;
    QRShape93: TQRShape;
    LabApp_7_0: TQRLabel;
    LabApp_7_1: TQRLabel;
    LabApp_7_2: TQRLabel;
    LabApp_7_4: TQRLabel;
    LabApp_7_5: TQRLabel;
    LabApp_7_6: TQRLabel;
    LabApp_7_7: TQRLabel;
    LabApp_7_3: TQRLabel;
    LabApp_7_8: TQRLabel;
    QRShape95: TQRShape;
    QRShape96: TQRShape;
    QRShape97: TQRShape;
    QRShape98: TQRShape;
    QRShape99: TQRShape;
    QRShape100: TQRShape;
    QRShape101: TQRShape;
    QRShape102: TQRShape;
    QRShape103: TQRShape;
    LabApp_8_0: TQRLabel;
    LabApp_8_1: TQRLabel;
    LabApp_8_2: TQRLabel;
    LabApp_8_4: TQRLabel;
    LabApp_8_5: TQRLabel;
    LabApp_8_6: TQRLabel;
    LabApp_8_7: TQRLabel;
    LabApp_8_3: TQRLabel;
    LabApp_8_8: TQRLabel;
    QRShape105: TQRShape;
    QRShape106: TQRShape;
    QRShape107: TQRShape;
    QRShape108: TQRShape;
    QRShape109: TQRShape;
    QRShape110: TQRShape;
    QRShape111: TQRShape;
    QRShape112: TQRShape;
    QRShape113: TQRShape;
    LabApp_9_0: TQRLabel;
    LabApp_9_1: TQRLabel;
    LabApp_9_2: TQRLabel;
    LabApp_9_4: TQRLabel;
    LabApp_9_5: TQRLabel;
    LabApp_9_6: TQRLabel;
    LabApp_9_7: TQRLabel;
    LabApp_9_3: TQRLabel;
    LabApp_9_8: TQRLabel;
    QRShape115: TQRShape;
    QRShape116: TQRShape;
    QRShape117: TQRShape;
    QRShape118: TQRShape;
    QRShape119: TQRShape;
    QRShape120: TQRShape;
    QRShape121: TQRShape;
    QRShape122: TQRShape;
    QRShape123: TQRShape;
    LabApp_10_0: TQRLabel;
    LabApp_10_1: TQRLabel;
    LabApp_10_2: TQRLabel;
    LabApp_10_4: TQRLabel;
    LabApp_10_5: TQRLabel;
    LabApp_10_6: TQRLabel;
    LabApp_10_7: TQRLabel;
    LabApp_10_3: TQRLabel;
    LabApp_10_8: TQRLabel;
    QRShape125: TQRShape;
    QRShape126: TQRShape;
    QRShape127: TQRShape;
    QRShape128: TQRShape;
    QRShape129: TQRShape;
    QRShape130: TQRShape;
    QRShape131: TQRShape;
    QRShape132: TQRShape;
    QRShape133: TQRShape;
    LabApp_11_0: TQRLabel;
    LabApp_11_1: TQRLabel;
    LabApp_11_2: TQRLabel;
    LabApp_11_4: TQRLabel;
    LabApp_11_5: TQRLabel;
    LabApp_11_6: TQRLabel;
    LabApp_11_7: TQRLabel;
    LabApp_11_3: TQRLabel;
    LabApp_11_8: TQRLabel;
    QRShape135: TQRShape;
    QRShape136: TQRShape;
    QRShape137: TQRShape;
    QRShape138: TQRShape;
    QRShape139: TQRShape;
    QRShape140: TQRShape;
    QRShape141: TQRShape;
    QRShape142: TQRShape;
    QRShape143: TQRShape;
    LabApp_12_0: TQRLabel;
    LabApp_12_1: TQRLabel;
    LabApp_12_2: TQRLabel;
    LabApp_12_4: TQRLabel;
    LabApp_12_5: TQRLabel;
    LabApp_12_6: TQRLabel;
    LabApp_12_7: TQRLabel;
    LabApp_12_3: TQRLabel;
    LabApp_12_8: TQRLabel;
    QRShape145: TQRShape;
    QRShape146: TQRShape;
    QRShape147: TQRShape;
    QRShape148: TQRShape;
    QRShape149: TQRShape;
    QRShape150: TQRShape;
    QRShape151: TQRShape;
    QRShape152: TQRShape;
    QRShape153: TQRShape;
    LabApp_13_0: TQRLabel;
    LabApp_13_1: TQRLabel;
    LabApp_13_2: TQRLabel;
    LabApp_13_4: TQRLabel;
    LabApp_13_5: TQRLabel;
    LabApp_13_6: TQRLabel;
    LabApp_13_7: TQRLabel;
    LabApp_13_3: TQRLabel;
    LabApp_13_8: TQRLabel;
    QRShape155: TQRShape;
    QRShape156: TQRShape;
    QRShape157: TQRShape;
    QRShape158: TQRShape;
    QRShape159: TQRShape;
    QRShape160: TQRShape;
    QRShape161: TQRShape;
    QRShape162: TQRShape;
    QRShape163: TQRShape;
    LabApp_14_0: TQRLabel;
    LabApp_14_1: TQRLabel;
    LabApp_14_2: TQRLabel;
    LabApp_14_4: TQRLabel;
    LabApp_14_5: TQRLabel;
    LabApp_14_6: TQRLabel;
    LabApp_14_7: TQRLabel;
    LabApp_14_3: TQRLabel;
    LabApp_14_8: TQRLabel;
    QRShape165: TQRShape;
    QRShape166: TQRShape;
    QRShape167: TQRShape;
    QRShape168: TQRShape;
    QRShape169: TQRShape;
    QRShape170: TQRShape;
    QRShape171: TQRShape;
    QRShape172: TQRShape;
    QRShape173: TQRShape;
    LabApp_15_0: TQRLabel;
    LabApp_15_1: TQRLabel;
    LabApp_15_2: TQRLabel;
    LabApp_15_4: TQRLabel;
    LabApp_15_5: TQRLabel;
    LabApp_15_6: TQRLabel;
    LabApp_15_7: TQRLabel;
    LabApp_15_3: TQRLabel;
    LabApp_15_8: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel1: TQRLabel;
    QRShape1: TQRShape;
    LabelCheckDM: TQRLabel;
    CheckDM: TQRLabel;
    QRShape2: TQRShape;
    QRLabel5: TQRLabel;
    CheckAltro: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel9: TQRLabel;
    QRShape14: TQRShape;
    QRShape24: TQRShape;
    QRLabel10: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel12: TQRLabel;
    QRShape34: TQRShape;
    QRLabel13: TQRLabel;
    CheckTenutaCamino: TQRLabel;
    QRLabel15: TQRLabel;
    QRLabel16: TQRLabel;
    QRMemo1: TQRMemo;
    QRMemo2: TQRMemo;
    QRMemo3: TQRMemo;
    LabelCopiaPer: TQRLabel;
    QRLabel18: TQRLabel;
    QRShape44: TQRShape;
    QRShape54: TQRShape;
    QRShape64: TQRShape;
    QRShape74: TQRShape;
    QRShape84: TQRShape;
    QRShape94: TQRShape;
    QRShape104: TQRShape;
    QRShape114: TQRShape;
    QRShape124: TQRShape;
    LabApp_16_0: TQRLabel;
    LabApp_16_1: TQRLabel;
    LabApp_16_2: TQRLabel;
    LabApp_16_4: TQRLabel;
    LabApp_16_5: TQRLabel;
    LabApp_16_6: TQRLabel;
    LabApp_16_7: TQRLabel;
    LabApp_16_3: TQRLabel;
    LabApp_16_8: TQRLabel;
    QRShape134: TQRShape;
    QRShape144: TQRShape;
    QRShape154: TQRShape;
    QRShape164: TQRShape;
    QRShape174: TQRShape;
    QRShape175: TQRShape;
    QRShape176: TQRShape;
    QRShape177: TQRShape;
    QRShape178: TQRShape;
    LabApp_17_0: TQRLabel;
    LabApp_17_1: TQRLabel;
    LabApp_17_2: TQRLabel;
    LabApp_17_4: TQRLabel;
    LabApp_17_5: TQRLabel;
    LabApp_17_6: TQRLabel;
    LabApp_17_7: TQRLabel;
    LabApp_17_3: TQRLabel;
    LabApp_17_8: TQRLabel;
    QRShape179: TQRShape;
    QRShape180: TQRShape;
    QRShape181: TQRShape;
    QRShape182: TQRShape;
    QRShape183: TQRShape;
    QRShape184: TQRShape;
    QRShape185: TQRShape;
    QRShape186: TQRShape;
    QRShape187: TQRShape;
    LabApp_18_0: TQRLabel;
    LabApp_18_1: TQRLabel;
    LabApp_18_2: TQRLabel;
    LabApp_18_4: TQRLabel;
    LabApp_18_5: TQRLabel;
    LabApp_18_6: TQRLabel;
    LabApp_18_7: TQRLabel;
    LabApp_18_3: TQRLabel;
    LabApp_18_8: TQRLabel;
    QRShape188: TQRShape;
    QRShape189: TQRShape;
    QRShape190: TQRShape;
    QRShape191: TQRShape;
    QRShape192: TQRShape;
    QRShape193: TQRShape;
    QRShape194: TQRShape;
    QRShape195: TQRShape;
    QRShape196: TQRShape;
    LabApp_19_0: TQRLabel;
    LabApp_19_1: TQRLabel;
    LabApp_19_2: TQRLabel;
    LabApp_19_4: TQRLabel;
    LabApp_19_5: TQRLabel;
    LabApp_19_6: TQRLabel;
    LabApp_19_7: TQRLabel;
    LabApp_19_3: TQRLabel;
    LabApp_19_8: TQRLabel;
    QRShape197: TQRShape;
    QRShape198: TQRShape;
    QRShape199: TQRShape;
    QRShape200: TQRShape;
    QRShape201: TQRShape;
    QRShape202: TQRShape;
    QRShape203: TQRShape;
    QRShape204: TQRShape;
    QRShape205: TQRShape;
    LabApp_20_0: TQRLabel;
    LabApp_20_1: TQRLabel;
    LabApp_20_2: TQRLabel;
    LabApp_20_4: TQRLabel;
    LabApp_20_5: TQRLabel;
    LabApp_20_6: TQRLabel;
    LabApp_20_7: TQRLabel;
    LabApp_20_3: TQRLabel;
    LabApp_20_8: TQRLabel;
    QRShape206: TQRShape;
    QRShape207: TQRShape;
    QRShape208: TQRShape;
    QRShape209: TQRShape;
    QRShape210: TQRShape;
    QRShape211: TQRShape;
    QRShape212: TQRShape;
    QRShape213: TQRShape;
    QRShape214: TQRShape;
    LabApp_21_0: TQRLabel;
    LabApp_21_1: TQRLabel;
    LabApp_21_2: TQRLabel;
    LabApp_21_4: TQRLabel;
    LabApp_21_5: TQRLabel;
    LabApp_21_6: TQRLabel;
    LabApp_21_7: TQRLabel;
    LabApp_21_3: TQRLabel;
    LabApp_21_8: TQRLabel;
    QRShape215: TQRShape;
    QRShape216: TQRShape;
    QRShape217: TQRShape;
    QRShape218: TQRShape;
    QRShape219: TQRShape;
    QRShape220: TQRShape;
    QRShape221: TQRShape;
    QRShape222: TQRShape;
    QRShape223: TQRShape;
    LabApp_22_0: TQRLabel;
    LabApp_22_1: TQRLabel;
    LabApp_22_2: TQRLabel;
    LabApp_22_4: TQRLabel;
    LabApp_22_5: TQRLabel;
    LabApp_22_6: TQRLabel;
    LabApp_22_7: TQRLabel;
    LabApp_22_3: TQRLabel;
    LabApp_22_8: TQRLabel;
    QRShape224: TQRShape;
    QRShape225: TQRShape;
    QRShape226: TQRShape;
    QRShape227: TQRShape;
    QRShape228: TQRShape;
    QRShape229: TQRShape;
    QRShape230: TQRShape;
    QRShape231: TQRShape;
    QRShape232: TQRShape;
    LabApp_23_0: TQRLabel;
    LabApp_23_1: TQRLabel;
    LabApp_23_2: TQRLabel;
    LabApp_23_4: TQRLabel;
    LabApp_23_5: TQRLabel;
    LabApp_23_6: TQRLabel;
    LabApp_23_7: TQRLabel;
    LabApp_23_3: TQRLabel;
    LabApp_23_8: TQRLabel;
    QRShape233: TQRShape;
    QRShape234: TQRShape;
    QRShape235: TQRShape;
    QRShape236: TQRShape;
    QRShape237: TQRShape;
    QRShape238: TQRShape;
    QRShape239: TQRShape;
    QRShape240: TQRShape;
    QRShape241: TQRShape;
    LabApp_24_0: TQRLabel;
    LabApp_24_1: TQRLabel;
    LabApp_24_2: TQRLabel;
    LabApp_24_4: TQRLabel;
    LabApp_24_5: TQRLabel;
    LabApp_24_6: TQRLabel;
    LabApp_24_7: TQRLabel;
    LabApp_24_3: TQRLabel;
    LabApp_24_8: TQRLabel;
    QRShape242: TQRShape;
    QRShape243: TQRShape;
    QRShape244: TQRShape;
    QRShape245: TQRShape;
    QRShape246: TQRShape;
    QRShape247: TQRShape;
    QRShape248: TQRShape;
    QRShape249: TQRShape;
    QRShape250: TQRShape;
    LabApp_25_0: TQRLabel;
    LabApp_25_1: TQRLabel;
    LabApp_25_2: TQRLabel;
    LabApp_25_4: TQRLabel;
    LabApp_25_5: TQRLabel;
    LabApp_25_6: TQRLabel;
    LabApp_25_7: TQRLabel;
    LabApp_25_3: TQRLabel;
    LabApp_25_8: TQRLabel;
    QRLabel120: TQRLabel;
    QRShape251: TQRShape;
    QRShape252: TQRShape;
    QRShape253: TQRShape;
    QRShape254: TQRShape;
    QRShape255: TQRShape;
    QRShape256: TQRShape;
    QRShape257: TQRShape;
    QRShape258: TQRShape;
    QRShape259: TQRShape;
    LabApp_26_0: TQRLabel;
    LabApp_26_1: TQRLabel;
    LabApp_26_2: TQRLabel;
    LabApp_26_4: TQRLabel;
    LabApp_26_5: TQRLabel;
    LabApp_26_6: TQRLabel;
    LabApp_26_7: TQRLabel;
    LabApp_26_3: TQRLabel;
    LabApp_26_8: TQRLabel;
    QRShape260: TQRShape;
    QRShape261: TQRShape;
    QRShape262: TQRShape;
    QRShape263: TQRShape;
    QRShape264: TQRShape;
    QRShape265: TQRShape;
    QRShape266: TQRShape;
    QRShape267: TQRShape;
    QRShape268: TQRShape;
    LabApp_27_0: TQRLabel;
    LabApp_27_1: TQRLabel;
    LabApp_27_2: TQRLabel;
    LabApp_27_4: TQRLabel;
    LabApp_27_5: TQRLabel;
    LabApp_27_6: TQRLabel;
    LabApp_27_7: TQRLabel;
    LabApp_27_3: TQRLabel;
    LabApp_27_8: TQRLabel;
    QRShape269: TQRShape;
    QRShape270: TQRShape;
    QRShape271: TQRShape;
    QRShape272: TQRShape;
    QRShape273: TQRShape;
    QRShape274: TQRShape;
    QRShape275: TQRShape;
    QRShape276: TQRShape;
    QRShape277: TQRShape;
    LabApp_28_0: TQRLabel;
    LabApp_28_1: TQRLabel;
    LabApp_28_2: TQRLabel;
    LabApp_28_4: TQRLabel;
    LabApp_28_5: TQRLabel;
    LabApp_28_6: TQRLabel;
    LabApp_28_7: TQRLabel;
    LabApp_28_3: TQRLabel;
    LabApp_28_8: TQRLabel;
    QRShape278: TQRShape;
    QRShape279: TQRShape;
    QRShape280: TQRShape;
    QRShape281: TQRShape;
    QRShape282: TQRShape;
    QRShape283: TQRShape;
    QRShape284: TQRShape;
    QRShape285: TQRShape;
    QRShape286: TQRShape;
    LabApp_29_0: TQRLabel;
    LabApp_29_1: TQRLabel;
    LabApp_29_2: TQRLabel;
    LabApp_29_4: TQRLabel;
    LabApp_29_5: TQRLabel;
    LabApp_29_6: TQRLabel;
    LabApp_29_7: TQRLabel;
    LabApp_29_3: TQRLabel;
    LabApp_29_8: TQRLabel;
    QRShape287: TQRShape;
    QRShape288: TQRShape;
    QRShape289: TQRShape;
    QRShape290: TQRShape;
    QRShape291: TQRShape;
    QRShape292: TQRShape;
    QRShape293: TQRShape;
    QRShape294: TQRShape;
    QRShape295: TQRShape;
    LabApp_30_0: TQRLabel;
    LabApp_30_1: TQRLabel;
    LabApp_30_2: TQRLabel;
    LabApp_30_4: TQRLabel;
    LabApp_30_5: TQRLabel;
    LabApp_30_6: TQRLabel;
    LabApp_30_7: TQRLabel;
    LabApp_30_3: TQRLabel;
    LabApp_30_8: TQRLabel;
    QRShape296: TQRShape;
    QRShape297: TQRShape;
    QRShape298: TQRShape;
    QRShape299: TQRShape;
    QRShape300: TQRShape;
    QRShape301: TQRShape;
    QRShape302: TQRShape;
    QRShape303: TQRShape;
    QRShape304: TQRShape;
    LabApp_31_0: TQRLabel;
    LabApp_31_1: TQRLabel;
    LabApp_31_2: TQRLabel;
    LabApp_31_4: TQRLabel;
    LabApp_31_5: TQRLabel;
    LabApp_31_6: TQRLabel;
    LabApp_31_7: TQRLabel;
    LabApp_31_3: TQRLabel;
    LabApp_31_8: TQRLabel;
    CheckTenutaTubazioni: TQRLabel;
    QRDBText4: TQRDBText;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRDBText3: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRLabel37: TQRLabel;
    QRLabelRifConformita: TQRLabel;
    procedure QuickRepBeforePrint(Sender: TCustomQuickRep;
      var PrintReport: Boolean);
  private
    FStampaElenchiEsterni: Boolean;
    procedure CaricaDatiGriglia;
  public
    property StampaElenchiEsterni:Boolean read FStampaElenchiEsterni write FStampaElenchiEsterni;
  end;

var
  All4690Pag3QR: TAll4690Pag3QR;

implementation

uses FormConformita, FormStampaDichiarazione, StrUtils, DataModule1;

{$R *.DFM}

// Carica i dati della griglia
procedure TAll4690Pag3QR.CaricaDatiGriglia;
var
  PrecPos: TBookmark;
  ix, iy: integer;
  CurrLabelName: String;
  CurrLabel: TQRLabel;
begin
  // Salva la posizione attuale e disabilita i controlli
  PrecPos := ConformitaForm.QryMat.Bookmark;
  try
    // DIsabilita i controlli per maggior velocità
    ConformitaForm.QryMat.DisableControls;
    // Cicla per tutti i record contenuti nella griglia delle apparecchiature
    for iy := 0 to MATERIALI_MAX_RIGHE -1 do begin
      // Cicla per tutte le colonne della stessa griglia
      for ix := 0 to ConformitaForm.tvMateriali.ColumnCount -1 do begin
        // Per comodità CurrLabel Punta alla label corrente.
        CurrLabelName := 'LabApp_' + IntToStr(iy) + '_' + IntToStr(ix);
        if (QRBandSchema.FindChildControl(CurrLabelName) <> nil) then begin
          CurrLabel := QRBandSchema.FindChildControl(CurrLabelName) as TQRLabel;
          // Se esiste il record corrispondente nella griglia carica il dato
          //  altrimenti la imposta che non stampa nulla.
          //  NB: Se si tratta del primo campo (Rif.) e il riferimento inizia con '(X' allora
          //       significa che si sta stampando un rigo che non è presente nel disegno
          //       e quindi non stampa il riferimento negli elenchi così l'utente ne può inserire lui
          //       uno a mano.
          if (iy < ConformitaForm.tvMateriali.DataController.RecordCount)
          and not (  (ix = 0) and (LeftStr(ConformitaForm.tvMateriali.DataController.GetDisplayText(iy, ix), 2) = '(X')  )
          and not StampaElenchiEsterni
          then CurrLabel.Caption := ConformitaForm.tvMateriali.DataController.GetDisplayText(iy, ix)
          else CurrLabel.Caption := '';
        end;
      end;
    end;
  finally
    // Rimette le cose a posto
    ConformitaForm.QryMat.Bookmark := PrecPos;
    ConformitaForm.QryMat.EnableControls;
  end;
  // Se si è scelto di stampare gli elenchi materiali esterni visualizza solo
  //  un rimando e poi esce.
  if StampaElenchiEsterni then begin
    LabApp_0_2.Font.Style := [fsBold];
    LabApp_0_2.Caption := 'Vedi Relazione allegata...';
  end;
end;




procedure TAll4690Pag3QR.QuickRepBeforePrint(Sender: TCustomQuickRep;
  var PrintReport: Boolean);
begin
  QRLabelRifConformita.Caption := 'Dichiarazione di conformità N.   ' + DM1.TableConformitaCODICE.AsString;

  CheckUNI.Enabled := ConformitaForm.DBCBUNI.Checked;
  CheckDM.Enabled := ConformitaForm.DBCBDM.Checked;
  CheckAltro.Enabled := ConformitaForm.DBCBAltro.Checked;
  CheckTenutaTubazioni.Enabled := ConformitaForm.DBCBTenutaTubazioni.Checked;
  CheckTenutaCamino.Enabled := ConformitaForm.DBCBTenutaCamino.Checked;
  CaricaDatiGriglia;
   // RIchiama il gestore di evento per l'impostazione della label COPIA PER...
   StampaDichiarazioneForm.EventoQRBeforePrint(Sender, PrintReport);
end;

end.
