unit QRAllegatoH;

interface
                                                                    
uses Windows, SysUtils, Messages, Classes, Graphics, Controls,
  ExtCtrls, Forms, QuickRpt, QRCtrls, IB_Components;

type
  TAllegatoHQR = class(TQuickRep)
    QRBand1: TQRBand;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRShape37: TQRShape;
    QRLabel96: TQRLabel;
    QRLabel3: TQRLabel;
    QRDBText62: TQRDBText;
    QRLabel4: TQRLabel;
    QRDBText1: TQRDBText;
    QRLabel5: TQRLabel;
    QRDBText2: TQRDBText;
    QRLabel6: TQRLabel;
    QRDBText3: TQRDBText;
    QRLabel7: TQRLabel;
    QRDBText4: TQRDBText;
    QRLabel8: TQRLabel;
    QRDBText5: TQRDBText;
    QRLabel9: TQRLabel;
    QRLabel11: TQRLabel;
    QRShape1: TQRShape;
    QRLabel10: TQRLabel;
    QRLabel12: TQRLabel;
    QRDBText9: TQRDBText;
    QRLabel13: TQRLabel;
    QRDBText8: TQRDBText;
    QRLabel14: TQRLabel;
    QRDBText10: TQRDBText;
    QRLabel15: TQRLabel;
    QRDBText11: TQRDBText;
    QRLabel16: TQRLabel;
    QRShape10: TQRShape;
    QRLabel53: TQRLabel;
    CameraTipoB: TQRLabel;
    QRShape6: TQRShape;
    QRLabel30: TQRLabel;
    CameraTipoC: TQRLabel;
    QRShape7: TQRShape;
    QRLabel32: TQRLabel;
    TiraggioNaturale: TQRLabel;
    QRShape8: TQRShape;
    QRLabel34: TQRLabel;
    TiraggioForzato: TQRLabel;
    QRShape9: TQRShape;
    QRLabel36: TQRLabel;
    CombustibileGasDiRete: TQRLabel;
    QRShape11: TQRShape;
    QRLabel38: TQRLabel;
    CombustibileGPL: TQRLabel;
    QRShape12: TQRShape;
    QRLabel40: TQRLabel;
    CombustibileGasolio: TQRLabel;
    QRShape13: TQRShape;
    QRLabel42: TQRLabel;
    CombustibileKerosene: TQRLabel;
    QRShape14: TQRShape;
    LabelCombustibileAltro: TQRLabel;
    CombustibileAltro: TQRLabel;
    QRLabel46: TQRLabel;
    QRDBText30: TQRDBText;
    QRShape15: TQRShape;
    QRShape16: TQRShape;
    QRLabel47: TQRLabel;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRLabel48: TQRLabel;
    QRShape19: TQRShape;
    QRShape20: TQRShape;
    QRDBText12: TQRDBText;
    QRLabel17: TQRLabel;
    QRDBText13: TQRDBText;
    QRLabel18: TQRLabel;
    QRDBText14: TQRDBText;
    QRShape2: TQRShape;
    QRLabel19: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel21: TQRLabel;
    QRLabel22: TQRLabel;
    QRShape3: TQRShape;
    QRLabel23: TQRLabel;
    QRShape4: TQRShape;
    QRLabel24: TQRLabel;
    QRShape5: TQRShape;
    QRLabel25: TQRLabel;
    QRLabel26: TQRLabel;
    QRLabel27: TQRLabel;
    QRLabel28: TQRLabel;
    QRLabel29: TQRLabel;
    QRLabel31: TQRLabel;
    QRLabel33: TQRLabel;
    QRLabel35: TQRLabel;
    QRLabel37: TQRLabel;
    QRLabel39: TQRLabel;
    QRLabel41: TQRLabel;
    QRLabel43: TQRLabel;
    QRLabel44: TQRLabel;
    QRLabel45: TQRLabel;
    QRLabel49: TQRLabel;
    QRLabel50: TQRLabel;
    QRLabel51: TQRLabel;
    QRLabel52: TQRLabel;
    QRLabel54: TQRLabel;
    QRLabel55: TQRLabel;
    QRLabel56: TQRLabel;
    QRLabel57: TQRLabel;
    QRLabel58: TQRLabel;
    QRLabel59: TQRLabel;
    QRLabel60: TQRLabel;
    QRLabel61: TQRLabel;
    QRLabel62: TQRLabel;
    QRLabel63: TQRLabel;
    QRLabel64: TQRLabel;
    QRLabel65: TQRLabel;
    QRLabel66: TQRLabel;
    QRLabel67: TQRLabel;
    QRLabel68: TQRLabel;
    QRLabel69: TQRLabel;
    QRLabel70: TQRLabel;
    QRLabel71: TQRLabel;
    QRLabel72: TQRLabel;
    QRLabel73: TQRLabel;
    QRLabel74: TQRLabel;
    QRLabel75: TQRLabel;
    QRLabel76: TQRLabel;
    QRLabel77: TQRLabel;
    QRLabel78: TQRLabel;
    QRLabel79: TQRLabel;
    QRLabel80: TQRLabel;
    QRLabel81: TQRLabel;
    QRLabel82: TQRLabel;
    QRLabel83: TQRLabel;
    QRLabel84: TQRLabel;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape23: TQRShape;
    QRShape24: TQRShape;
    QRShape25: TQRShape;
    QRShape26: TQRShape;
    QRShape27: TQRShape;
    QRShape28: TQRShape;
    QRShape29: TQRShape;
    QRShape30: TQRShape;
    QRShape31: TQRShape;
    QRShape32: TQRShape;
    QRShape33: TQRShape;
    QRLabel85: TQRLabel;
    QRShape34: TQRShape;
    QRLabel86: TQRLabel;
    QRShape35: TQRShape;
    QRLabel87: TQRLabel;
    QRShape36: TQRShape;
    QRLabel88: TQRLabel;
    QRShape38: TQRShape;
    QRLabel89: TQRLabel;
    QRShape39: TQRShape;
    QRLabel90: TQRLabel;
    QRShape40: TQRShape;
    QRLabel91: TQRLabel;
    QRShape41: TQRShape;
    QRLabel92: TQRLabel;
    QRShape42: TQRShape;
    QRLabel93: TQRLabel;
    QRShape43: TQRShape;
    QRLabel94: TQRLabel;
    QRShape44: TQRShape;
    QRLabel95: TQRLabel;
    QRShape45: TQRShape;
    QRLabel97: TQRLabel;
    QRShape46: TQRShape;
    QRLabel98: TQRLabel;
    QRShape47: TQRShape;
    QRLabel99: TQRLabel;
    QRShape48: TQRShape;
    QRLabel101: TQRLabel;
    QRShape49: TQRShape;
    QRLabel102: TQRLabel;
    QRShape50: TQRShape;
    QRLabel103: TQRLabel;
    QRShape51: TQRShape;
    QRLabel104: TQRLabel;
    QRShape52: TQRShape;
    QRLabel105: TQRLabel;
    QRShape53: TQRShape;
    QRLabel106: TQRLabel;
    QRShape54: TQRShape;
    QRLabel107: TQRLabel;
    QRShape55: TQRShape;
    QRLabel108: TQRLabel;
    QRShape56: TQRShape;
    QRLabel109: TQRLabel;
    QRShape57: TQRShape;
    QRLabel110: TQRLabel;
    QRShape58: TQRShape;
    QRLabel111: TQRLabel;
    QRShape59: TQRShape;
    QRLabel112: TQRLabel;
    QRShape60: TQRShape;
    QRLabel113: TQRLabel;
    QRShape61: TQRShape;
    QRLabel114: TQRLabel;
    QRShape62: TQRShape;
    QRLabel115: TQRLabel;
    QRShape63: TQRShape;
    QRLabel116: TQRLabel;
    QRShape64: TQRShape;
    QRLabel117: TQRLabel;
    QRShape65: TQRShape;
    QRLabel118: TQRLabel;
    QRShape66: TQRShape;
    QRLabel119: TQRLabel;
    QRShape67: TQRShape;
    QRLabel120: TQRLabel;
    QRShape68: TQRShape;
    QRLabel121: TQRLabel;
    QRShape69: TQRShape;
    QRLabel122: TQRLabel;
    QRShape70: TQRShape;
    QRLabel123: TQRLabel;
    QRShape71: TQRShape;
    QRLabel124: TQRLabel;
    QRShape72: TQRShape;
    QRLabel125: TQRLabel;
    QRShape73: TQRShape;
    QRLabel126: TQRLabel;
    QRShape74: TQRShape;
    QRLabel127: TQRLabel;
    QRShape75: TQRShape;
    QRLabel128: TQRLabel;
    QRShape76: TQRShape;
    QRLabel129: TQRLabel;
    QRShape77: TQRShape;
    QRLabel130: TQRLabel;
    QRShape78: TQRShape;
    QRLabel131: TQRLabel;
    QRShape79: TQRShape;
    QRLabel132: TQRLabel;
    QRShape80: TQRShape;
    QRLabel133: TQRLabel;
    QRShape81: TQRShape;
    QRLabel134: TQRLabel;
    QRShape82: TQRShape;
    QRLabel135: TQRLabel;
    QRShape83: TQRShape;
    QRLabel136: TQRLabel;
    QRShape84: TQRShape;
    QRLabel137: TQRLabel;
    QRShape85: TQRShape;
    QRLabel138: TQRLabel;
    QRShape86: TQRShape;
    QRLabel139: TQRLabel;
    QRShape87: TQRShape;
    QRLabel140: TQRLabel;
    QRShape88: TQRShape;
    QRLabel141: TQRLabel;
    QRShape89: TQRShape;
    QRLabel142: TQRLabel;
    QRShape90: TQRShape;
    QRLabel143: TQRLabel;
    QRShape91: TQRShape;
    QRLabel144: TQRLabel;
    QRShape92: TQRShape;
    QRLabel145: TQRLabel;
    QRShape93: TQRShape;
    QRLabel146: TQRLabel;
    QRShape94: TQRShape;
    QRLabel147: TQRLabel;
    QRShape95: TQRShape;
    QRLabel148: TQRLabel;
    QRShape96: TQRShape;
    QRLabel149: TQRLabel;
    QRShape97: TQRShape;
    QRLabel150: TQRLabel;
    QRShape98: TQRShape;
    QRLabel151: TQRLabel;
    QRShape99: TQRShape;
    QRLabel152: TQRLabel;
    QRShape100: TQRShape;
    QRLabel153: TQRLabel;
    QRShape101: TQRShape;
    QRLabel154: TQRLabel;
    QRShape102: TQRShape;
    QRLabel155: TQRLabel;
    QRShape103: TQRShape;
    QRLabel156: TQRLabel;
    QRShape104: TQRShape;
    QRLabel157: TQRLabel;
    QRShape105: TQRShape;
    QRLabel158: TQRLabel;
    QRShape106: TQRShape;
    QRLabel159: TQRLabel;
    QRShape107: TQRShape;
    QRLabel160: TQRLabel;
    QRShape108: TQRShape;
    QRLabel161: TQRLabel;
    QRShape109: TQRShape;
    QRLabel162: TQRLabel;
    QRShape110: TQRShape;
    QRLabel163: TQRLabel;
    QRShape111: TQRShape;
    QRLabel164: TQRLabel;
    QRShape112: TQRShape;
    QRLabel165: TQRLabel;
    QRShape113: TQRShape;
    QRLabel166: TQRLabel;
    QRShape114: TQRShape;
    QRLabel167: TQRLabel;
    QRShape115: TQRShape;
    QRLabel168: TQRLabel;
    QRShape116: TQRShape;
    QRLabel169: TQRLabel;
    QRShape117: TQRShape;
    QRLabel170: TQRLabel;
    QRShape118: TQRShape;
    QRLabel171: TQRLabel;
    QRShape119: TQRShape;
    QRLabel172: TQRLabel;
    QRShape120: TQRShape;
    QRLabel173: TQRLabel;
    QRLabel174: TQRLabel;
    QRLabel175: TQRLabel;
    QRLabel176: TQRLabel;
    QRLabel177: TQRLabel;
    QRLabel178: TQRLabel;
    QRLabel179: TQRLabel;
    QRLabel180: TQRLabel;
    QRLabel181: TQRLabel;
    QRLabel182: TQRLabel;
    QRLabel183: TQRLabel;
    QRShape121: TQRShape;
    QRLabel184: TQRLabel;
    QRShape122: TQRShape;
    QRLabel185: TQRLabel;
    QRLabel186: TQRLabel;
    QRShape123: TQRShape;
    QRLabel187: TQRLabel;
    QRLabel188: TQRLabel;
    QRShape124: TQRShape;
    QRLabel189: TQRLabel;
    QRShape125: TQRShape;
    QRLabel100: TQRLabel;
    QRLabel190: TQRLabel;
    QRShape126: TQRShape;
    QRShape127: TQRShape;
    QRLabel191: TQRLabel;
    QRShape128: TQRShape;
    QRLabel192: TQRLabel;
    QRShape129: TQRShape;
    QRLabel193: TQRLabel;
    QRShape130: TQRShape;
    QRLabel194: TQRLabel;
    QRShape131: TQRShape;
    QRLabel195: TQRLabel;
    QRShape132: TQRShape;
    QRLabel196: TQRLabel;
    QRShape135: TQRShape;
    QRShape136: TQRShape;
    QRShape137: TQRShape;
    QRShape133: TQRShape;
    QRLabel197: TQRLabel;
    QRShape134: TQRShape;
    QRShape138: TQRShape;
    QRShape139: TQRShape;
    QRShape140: TQRShape;
    QRLabel198: TQRLabel;
    QRShape141: TQRShape;
    QRShape142: TQRShape;
    QRShape143: TQRShape;
    QRLabel199: TQRLabel;
    QRMemo1: TQRMemo;
    QRMemo2: TQRMemo;
    QRShape144: TQRShape;
    QRLabel200: TQRLabel;
    QRLabel201: TQRLabel;
    QRDBText15: TQRDBText;
    QRShape145: TQRShape;
    QRLabel202: TQRLabel;
    QRShape146: TQRShape;
    QRLabel203: TQRLabel;
    QRShape147: TQRShape;
    QRLabel204: TQRLabel;
    QRShape148: TQRShape;
    QRLabel205: TQRLabel;
    QRShape149: TQRShape;
    QRShape150: TQRShape;
    QRLabel207: TQRLabel;
    QRLabel206: TQRLabel;
    Proprietario: TQRLabel;
    Utente: TQRLabel;
    QRLabelTecnicoNome: TQRLabel;
    QRLabelTecnicoIndirizzo: TQRLabel;
    QRLabelTecnicoEstremiDocQualifica: TQRLabel;
    procedure QuickRepBeforePrint(Sender: TCustomQuickRep;
      var PrintReport: Boolean);
  private
    procedure CaricaDatiTecnico(ID: Integer);

  public

  end;

var
  AllegatoHQR: TAllegatoHQR;

implementation

uses FormImpegni, DataModule1;

{$R *.DFM}

procedure TAllegatoHQR.CaricaDatiTecnico(ID:Longint);
var
  Q:TIB_Cursor;
begin
  // Inizializzazione
  QRLabelTecnicoNome.Caption := '';
  QRLabelTecnicoIndirizzo.Caption := '';
  QRLabelTecnicoEstremiDocQualifica.Caption := '';
  Q := TIB_Cursor.Create(nil);
  try
    Q.DatabaseName  := DM1.ArcDBFile;
    Q.IB_Connection := DM1.DBAzienda;
    Q.SQL.Add('SELECT NOME, INDIRIZZO, CITTA, PROVINCIA, TELEFONO, ESTREMIDOCQUALIFICA FROM TECNICI WHERE RESOURCEID = ' + IntToStr(ID));
    Q.Open;
    if Q.Eof then Exit;
    QRLabelTecnicoNome.Caption := Q.FieldByName('NOME').AsString;
    QRLabelTecnicoIndirizzo.Caption := Q.FieldByName('INDIRIZZO').AsString + ' ' + Q.FieldByName('CITTA').AsString + ' '  + Q.FieldByName('PROVINCIA').AsString;
    QRLabelTecnicoEstremiDocQualifica.Caption := Q.FieldByName('ESTREMIDOCQUALIFICA').AsString;
  finally
    Q.Free;
  end;
end;


procedure TAllegatoHQR.QuickRepBeforePrint(Sender: TCustomQuickRep;
  var PrintReport: Boolean);
var
   TmpStr : String;   // Variabile di appoggio temporanea
begin
   // Carica i dati del tecnico
   CaricaDatiTecnico(ImpegnoForm.QryImpRESOURCEID.AsInteger);
   // Imposta il tipo camera
   TmpStr := ImpegnoForm.QryAssTIPOCAMERA.AsString;
   CameraTipoB.Enabled := (TmpStr = 'Tipo B');
   CameraTipoC.Enabled := (TmpStr = 'Tipo C');
   // Imposta il tipo di tiraggio
   TmpStr := ImpegnoForm.QryAssTIPOTIRAGGIO.AsString;
   TiraggioNaturale.Enabled   := (TmpStr = 'Naturale');
   TiraggioForzato.Enabled    := (TmpStr = 'Forzato');
   // Imposta il tipo di tiraggio
   TmpStr := ImpegnoForm.QryAssCOMBUSTIBILE.AsString;
   CombustibileGasDiRete.Enabled  := (TmpStr = 'Gas di rete');
   CombustibileGPL.Enabled        := (TmpStr = 'GPL');
   CombustibileGasolio.Enabled    := (TmpStr = 'Gasolio');
   CombustibileKerosene.Enabled   := (TmpStr = 'Kerosene');
   CombustibileAltro.Enabled      := (TmpStr = 'Altro');
   // Costruzione del proprietario
   Proprietario.Caption := ImpegnoForm.QryImpRAGSOCCLI.AsString
                 + ' - ' + ImpegnoForm.QryImpINDIRIZZOCLI.AsString
                 + ' - ' + ImpegnoForm.QryImpCAPCLI.AsString
                 + ' - ' + ImpegnoForm.QryImpCITTACLI.AsString
                 + ' ('  + ImpegnoForm.QryImpPROVINCIACLI.AsString + ')';
   // Costruzione dell'utente
   Utente.Caption := ImpegnoForm.QryAssRAGSOCUT.AsString;
end;

end.
