unit iORM.DBBuilder.SqlScript.Base;

interface

uses
  System.Classes,

  iORM.DBBuilder.Interfaces,
  iORM.CommonTypes,
  iORM.DB.Consts

  ;


type
  TioDBBuilderSqlScript = class(TInterfacedObject, IioDBBuilderSqlScript)
  private
    FIndentation: TioIndentation;
    FScript: TStringList;
    FSeparatorLength: integer;
    function GetSQL: TStringList;
    function GetCurrentIndentation: TioIndentation;
  protected
    function GetIndentation: String;
  public
    constructor Create(const AIndentationWidth: integer = SCRIPT_INDENTATION_WIDTH; const ASeparatorLength: integer = SCRIPT_SEPARATOR_LENGTH);
    destructor Destroy; override;

    procedure Add(const AText: String; const UseIndent: boolean = True); virtual;
    procedure AddComment(const AText: String); virtual;
    procedure AddEmpty; virtual;
    procedure AddSeparator; virtual;
    procedure AddTitle(const AText: String); virtual;
    procedure AddWarning(const AText: String); virtual;
    procedure AddWarnings(const WarningsList: TStrings); virtual;

    procedure DecIndentationLevel;
    procedure IncIndentationLevel;

    procedure ScriptBegin(const AConnectionDefName, ADriverID: string); virtual;
    procedure ScriptEnd; virtual;

    property CurrentIndentation: TioIndentation read GetCurrentIndentation;
    property SQL: TStringList read GetSQL;
  end;

implementation

uses
  System.SysUtils,

  iORM.DB.ConnectionContainer

  ;


{ TioDBBuilderSqlScript }

procedure TioDBBuilderSqlScript.Add(const AText: String; const UseIndent: boolean = True);
begin
  if UseIndent then
    FScript.Add(GetIndentation + AText)
  else
    FScript.Add(AText);
end;

procedure TioDBBuilderSqlScript.AddComment(const AText: String);
begin
  FScript.Add('-- ' + AText);
end;

procedure TioDBBuilderSqlScript.AddEmpty;
begin
  FScript.Add('');
end;

procedure TioDBBuilderSqlScript.AddSeparator;
begin
  FScript.Add(StringOfChar('-', FSeparatorLength));
end;

procedure TioDBBuilderSqlScript.AddTitle(const AText: String);
begin
  AddEmpty;
  AddSeparator;
  AddComment(AText);
  AddSeparator;
  AddEmpty;
end;

procedure TioDBBuilderSqlScript.AddWarning(const AText: String);
begin
  AddComment(Format('WARNING:  %s',  [AText]));
end;

procedure TioDBBuilderSqlScript.AddWarnings(const WarningsList: TStrings);
var
  LWarning: String;
begin
  AddTitle('W A R N I N G S !!!        W A R N I N G S !!!        W A R N I N G S !!! --');

  for LWarning in WarningsList do
    AddWarning(LWarning);
end;

constructor TioDBBuilderSqlScript.Create(const AIndentationWidth: integer; const ASeparatorLength: integer);
begin
  inherited Create;

  FIndentation := TioIndentation.Create(AIndentationWidth);
  FSeparatorLength := ASeparatorLength;
  FScript := TStringList.Create;
end;

procedure TioDBBuilderSqlScript.DecIndentationLevel;
begin
  FIndentation.DecIndent;
end;

destructor TioDBBuilderSqlScript.Destroy;
begin
  FScript.Free;

  inherited;
end;

function TioDBBuilderSqlScript.GetCurrentIndentation: TioIndentation;
begin
  Result := FIndentation;
end;

function TioDBBuilderSqlScript.GetIndentation: String;
begin
  Result := FIndentation.IndentChars;
end;

function TioDBBuilderSqlScript.GetSQL: TStringList;
begin
  Result := FScript;
end;

procedure TioDBBuilderSqlScript.IncIndentationLevel;
begin
  FIndentation.IncIndent;
end;

procedure TioDBBuilderSqlScript.ScriptBegin(const AConnectionDefName, ADriverID: string);
begin
  AddSeparator;
  AddComment('Start of the script generated by iORM');
  AddSeparator;
  AddComment('Date - time....: ' + FormatDateTime('d mmm yyyy - hh:nn:ss', Now));
  AddComment('Connection name: ' + AConnectionDefName);
  AddComment('DBMS...........: ' + ADriverID);
  AddSeparator;
end;

procedure TioDBBuilderSqlScript.ScriptEnd;
begin
  AddSeparator;
  AddComment('End of the script generated by iORM');
  AddSeparator;
end;

end.
