{
  ****************************************************************************
  *                                                                          *
  *           iORM - (interfaced ORM)                                        *
  *                                                                          *
  *           Copyright (C) 2015-2023 Maurizio Del Magno                     *
  *                                                                          *
  *           mauriziodm@levantesw.it                                        *
  *           mauriziodelmagno@gmail.com                                     *
  *           https://github.com/mauriziodm/iORM.git                         *
  *                                                                          *
  ****************************************************************************
  *                                                                          *
  * This file is part of iORM (Interfaced Object Relational Mapper).         *
  *                                                                          *
  * Licensed under the GNU Lesser General Public License, Version 3;         *
  *  you may not use this file except in compliance with the License.        *
  *                                                                          *
  * iORM is free software: you can redistribute it and/or modify             *
  * it under the terms of the GNU Lesser General Public License as published *
  * by the Free Software Foundation, either version 3 of the License, or     *
  * (at your option) any later version.                                      *
  *                                                                          *
  * iORM is distributed in the hope that it will be useful,                  *
  * but WITHOUT ANY WARRANTY; without even the implied warranty of           *
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            *
  * GNU Lesser General Public License for more details.                      *
  *                                                                          *
  * You should have received a copy of the GNU Lesser General Public License *
  * along with iORM.  If not, see <http://www.gnu.org/licenses/>.            *
  *                                                                          *
  ****************************************************************************
}
unit iORM.DBBuilder.Engine;

interface

uses
  System.Classes,

  iORM.CommonTypes,
  iORM.Context.Table.Interfaces,
  iORM.DBBuilder.Interfaces,
  iORM.DBBuilder.SqlScript.Base

  ;

type

  TioDBBuilderEngine_New = class
  private
    FBuildForeignKeys: Boolean;
    FBuildIndexes: Boolean;
    FConnectionDefName: string;
    FForceToCreateNewDB: Boolean;
    FSchema: IioDBBuilderSchema;
    FScript: IioDBBuilderSqlScript;
    FSqlGenerator: IioDBBuilderSqlGenerator;

    procedure CreateDatabasePhys;
    function GetDBStatus: TioDBBuilderStatus;
    function GetSchema: IioDBBuilderSchema;
    function GetScript: IioDBBuilderSqlScript;
    function GetTableStatus(const ATableName: String): TioDBBuilderStatus;
    function GetWarnings: TStrings;
  public
    constructor Create(const AConnectionDefName: String; const ABuildIndexes, ABuildForeignKeys, AForceCreateNewDB: Boolean);

    procedure CreateOrUpdateDB(const AForce: Boolean = False);
    procedure CreateOrUpdateTable(const ATableName: String);
    procedure RebuildSchema;
    procedure RebuildScript;

    property DBStatus: TioDBBuilderStatus read GetDBStatus;
    property Schema: IioDBBuilderSchema read GetSchema;
    property Script: IioDBBuilderSqlScript read GetScript;
    property TableStatus[const TableName: String]: TioDBBuilderStatus read GetTableStatus;
    property Warnings: TStrings read GetWarnings;
  end;




  TioDBBuilderEngine = class(TInterfacedObject, IioDBBuilderEngine)
  private
    FAnalyzed: boolean;
    FConnectionDefName: string;
    FSchema: IioDBBuilderSchema;
    FSqlGenerator: IioDBBuilderSqlGenerator;
    procedure CreateDatabase;
    function GetWarnings: TStrings;
    function GetSchema: IioDBBuilderSchema;
    function GetAnalyzed: boolean;
  protected
  public
    constructor Create(const AConnectionDefName: String; const AddIndexes, AddForeignKeys: Boolean);

    /// <summary>
    ///  Analyzes the schema generated by entities mapping and current database schema updating the schema status.
    ///  It must be called before CreateOrAlterDB, BuildCreateDBSqlScript, BuildUpdateDBSqlScript or BuildCreateOrAlterDBSqlScript methods.
    /// <param name="ForceCreate">Forces the analyzer to act if the database should be created</param>
    /// <remarks>
    ///  If the ForceCreate parameter is true, the analyzer behaves like the database doesn't exists and should be created even if it already exists.
    ///  If the ForceCreate parameter is false, the analyzer behaves like normal, acting as if the database doesn't exists if not exists or updated it if already exists.
    /// </remarks>
    /// </summary>
    function Analyze(const ForceCreate: boolean = False): TioDBBuilderStatus;
    /// <summary>
    ///  Build Creates or Alter database SQL script based on schema status.
    /// <param name="AScript">The script where sql instructions will be returned.</param>
    /// </summary>
    procedure BuildCreateOrUpdateDBSqlScript(const AScript: IioDBBuilderSqlScript);
    /// <summary>
    ///  Build Creates database SQL script regardless of schema status.
    /// <param name="AScript">The script where sql instructions will be returned.</param>
    /// </summary>
    procedure BuildCreateDBSqlScript(const AScript: IioDBBuilderSqlScript);

    procedure BuildDropIndexesSqlScript(const AScript: IioDBBuilderSqlScript);

    procedure BuildDropForeignKeysSqlScript(const AScript: IioDBBuilderSqlScript);
    /// <summary>
    ///  Build update database SQL script regardless of schema status.
    /// <param name="AScript">The script where sql instructions will be returned.</param>
    /// </summary>
    procedure BuildUpdateDBSqlScript(const AScript: IioDBBuilderSqlScript);
    /// <summary>
    ///  Creates or update the database depending on the actual schema/database status.
    ///  No need to call Analyze because it is called internally.
    /// <param name="Force">Forces the execution regardless of the schema status.</param>
    /// </summary>
    procedure CreateOrUpdateDB(const Force: Boolean = False; const AScript: IioDBBuilderSqlScript = nil); overload;
    /// <summary>
    ///  Creates or update the the table depending on the actual schema status.
    /// <param name="ATable">Schema of the table to be created/updated.</param>
    /// <param name="AddIndexes">Enable/Disable the creation table indexes.</param>
    /// <param name="AddForeignKeys">Enabled/Disable the creation of table foreign keys.</param>
    /// </summary>
    procedure CreateOrUpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean = True; const AddForeignKeys: Boolean = True);
    /// <summary>
    ///  Creates the table using the schema passed.
    /// <param name="ATable">Schema of the table to be created/updated.</param>
    /// <param name="AddIndexes">Enable/Disable the creation table indexes.</param>
    /// <param name="AddForeignKeys">Enabled/Disable the creation of table foreign keys.</param>
    /// </summary>
    procedure CreateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean = True; const AddForeignKeys: Boolean = True);
    /// <summary>
    ///  Updates the table using the schema passed.
    /// <param name="ATable">Schema of the table to be created/updated.</param>
    /// <param name="AddIndexes">Enable/Disable the creation table indexes.</param>
    /// <param name="AddForeignKeys">Enabled/Disable the creation of table foreign keys.</param>
    /// </summary>
    procedure UpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean = True; const AddForeignKeys: Boolean = True);

    property Analyzed: boolean read GetAnalyzed;
    property Schema: IioDBBuilderSchema read GetSchema;
    property Warnings: TStrings read GetWarnings;
  end;

implementation

uses
  System.SysUtils,
  System.TypInfo,

  iORM.DBBuilder.Factory,
  iORM.DBBuilder.Schema,
  iORM.DB.Consts,
  iORM.DB.Factory,
  iORM.Exceptions

  ;

{ TioDBBuilderEngine }

function TioDBBuilderEngine.Analyze(const ForceCreate: boolean): TioDBBuilderStatus;
var
  LDBAnalyzer: IioDBBuilderDBAnalyzer;
begin
  LDBAnalyzer := TioDBBuilderFactory.NewDBAnalyzer(FConnectionDefName, FSchema, FSqlGenerator, ForceCreate);
  LDBAnalyzer.Analyze;
  FAnalyzed := True;

  Result := FSchema.Status;
end;

procedure TioDBBuilderEngine.BuildCreateDBSqlScript(const AScript: IioDBBuilderSqlScript);
begin
  if not Assigned(AScript) then
    raise EArgumentNilException.CreateFmt('%s.%s: %s', [ClassName, 'BuildCreateDBSqlScript', 'AScript is not assigned.']);

  if not Analyzed then
    raise EioGenericException.Create(ClassName, 'BuildCreateDBSqlScript', 'Unable to build SQL script: schema not analyzed');

  TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, AScript).GenerateCreateDatabaseScript;
end;

procedure TioDBBuilderEngine.BuildCreateOrUpdateDBSqlScript(const AScript: IioDBBuilderSqlScript);
begin
  if not Analyzed then
    raise EioGenericException.Create(ClassName, 'BuildCreateOrUpdateDBSqlScript', 'Unable to build SQL script: schema not analyzed');

  if not Assigned(AScript) then
    raise EioInvalidArgumentException.Create(ClassName, 'BuildCreateOrUpdateDBSqlScript', 'AScript is not assigned.');

  case Schema.Status of
    stCreate: TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, AScript).GenerateCreateDatabaseScript;
    stUpdate: TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, AScript).GenerateUpdateDatabaseScript;
  end;
end;

procedure TioDBBuilderEngine.BuildDropForeignKeysSqlScript(const AScript: IioDBBuilderSqlScript);
begin
  if not Assigned(AScript) then
    raise EArgumentNilException.CreateFmt('%s.%s: %s', [ClassName, 'BuildDropForeignKeysSqlScript', 'AScript is not assigned.']);

  TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, AScript).DropForeignKeys;
end;

procedure TioDBBuilderEngine.BuildDropIndexesSqlScript(const AScript: IioDBBuilderSqlScript);
begin
  if not Assigned(AScript) then
    raise EArgumentNilException.CreateFmt('%s.%s: %s', [ClassName, 'BuildDropIndexesSqlScript', 'AScript is not assigned.']);

  TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, AScript).DropIndexes;
end;

procedure TioDBBuilderEngine.BuildUpdateDBSqlScript(const AScript: IioDBBuilderSqlScript);
begin
  if not Assigned(AScript) then
    raise EioInvalidArgumentException.Create(ClassName, 'BuildUpdateDBSqlScript', 'AScript is not assigned.');

  if not Analyzed then
    raise EioGenericException.Create(ClassName, 'BuildUpdateDBSqlScript', 'Unable to build SQL script: schema not analyzed');

  TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, AScript).GenerateUpdateDatabaseScript;
end;

constructor TioDBBuilderEngine.Create(const AConnectionDefName: String; const AddIndexes, AddForeignKeys: Boolean);
begin
  FAnalyzed := False;
  FConnectionDefName := AConnectionDefName;
  FSchema := TioDBBuilderFactory.NewSchema(FConnectionDefName, AddIndexes, AddForeignKeys);
  FSqlGenerator := TioDBBuilderFactory.NewSqlGenerator(FConnectionDefName);
end;

procedure TioDBBuilderEngine.CreateDatabase;
var
  LStrategy: IioDBBuilderStrategy;
begin
  if not Analyzed then
    raise EioGenericException.Create(ClassName, 'CreateDatabase', 'Unable to create database: schema not analyzed');

  LStrategy := TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, nil);
  LStrategy.CreateDatabase;
end;

procedure TioDBBuilderEngine.CreateOrUpdateDB(const Force: Boolean; const AScript: IioDBBuilderSqlScript);
var
  LScript: IioDBBuilderSqlScript;
  LBuildScript: boolean;
  LStatus: TioDBBuilderStatus;
begin
  LBuildScript := not Assigned(AScript);

  // Carlo Marona (2025-10-15): Do not pass Force param of this method to Analyze method. They have different behavior
  if LBuildScript then
    LStatus := Analyze
  else
    LStatus := Schema.Status;

  if (LStatus > stClean) or Force then
  begin
    if Schema.WarningExists then
      raise EioGenericException.Create(ClassName, 'CreateOrUpdateDB',
        'Database must be updated but WARNINGS exists.' + sLineBreak +
        FSchema.Warnings.Text
      );

    if LBuildScript then
      LScript := TioDBBuilderFactory.NewSqlScript
    else
      LScript := AScript;

    if LStatus = stCreate then
    begin
      // Carlo Marona: create the database fisically, on the server or as a file depending on database type used
      CreateDatabase;

      if LBuildScript then
        BuildCreateDBSqlScript(LScript);
    end
    else if LStatus = stUpdate then
    begin
      if LBuildScript then
        BuildUpdateDBSqlScript(LScript);
    end;

    TioDBFactory.Script(FConnectionDefName, LScript.SQL).Execute;
  end;
end;

procedure TioDBBuilderEngine.CreateOrUpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean;
  const AddForeignKeys: Boolean);
begin
  if not Assigned(ATable) then
    raise EioInvalidArgumentException.Create(ClassName, 'CreateOrUpdateTable', 'ATable is not assigned.');

  case ATable.Status of
    stCreate: CreateTable(ATable, AddIndexes, AddForeignKeys);
    stUpdate: UpdateTable(ATable, AddIndexes, AddForeignKeys);
  end;
end;

procedure TioDBBuilderEngine.CreateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean;
  const AddForeignKeys: Boolean);
var
  LStrategy: IioDBBuilderStrategy;
  LScript: IioDBBuilderSqlScript;
begin
  if not Assigned(ATable) then
    raise EioInvalidArgumentException.Create(ClassName, 'CreateTable', 'ATable is not assigned.');

  if ATable.Status <> stCreate then
    exit;

  LScript := TioDBBuilderFactory.NewSqlScript;
  LStrategy := TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, LScript);

  LStrategy.CreateTable(ATable);

  if AddForeignKeys then
    LStrategy.CreateTableForeignKeys(ATable);

  TioDBFactory.Script(FConnectionDefName, LScript.SQL).Execute;
end;

procedure TioDBBuilderEngine.UpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean;
  const AddForeignKeys: Boolean);
var
  LStrategy: IioDBBuilderStrategy;
  LScript: IioDBBuilderSqlScript;
begin
  if not Assigned(ATable) then
    raise EioInvalidArgumentException.Create(ClassName, 'UpdateTable', 'ATable is not assigned.');

  if ATable.Status <> stCreate then
    exit;

  LScript := TioDBBuilderFactory.NewSqlScript;
  LStrategy := TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, LScript);

  LStrategy.AlterTable(ATable);
  TioDBFactory.Script(FConnectionDefName, LScript.SQL).Execute;
end;

function TioDBBuilderEngine.GetAnalyzed: boolean;
begin
  Result := FAnalyzed;
end;

function TioDBBuilderEngine.GetSchema: IioDBBuilderSchema;
begin
  Result := FSchema;
end;

function TioDBBuilderEngine.GetWarnings: TStrings;
begin
  Result := FSchema.Warnings;
end;

{ TioDBBuilderEngine_New }
constructor TioDBBuilderEngine_New.Create(const AConnectionDefName: String; const ABuildIndexes, ABuildForeignKeys, AForceCreateNewDB: Boolean);
begin
  FBuildForeignKeys := ABuildForeignKeys;
  FBuildIndexes := ABuildIndexes;
  FConnectionDefName := AConnectionDefName;
  FForceToCreateNewDB := AForceCreateNewDB;

  FSqlGenerator := TioDBBuilderFactory.NewSqlGenerator(AConnectionDefName);
  RebuildSchema;
  RebuildScript;
end;

procedure TioDBBuilderEngine_New.CreateDatabasePhys;
begin
  TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, nil).CreateDatabase;
end;

procedure TioDBBuilderEngine_New.CreateOrUpdateDB(const AForce: Boolean);
begin
  if (FSchema.Status > stClean) or AForce then
  begin
    if FSchema.WarningExists then
      raise EioGenericException.Create(ClassName, 'CreateOrUpdateDB', 'Database must be updated but WARNINGS exists.' + sLineBreak + FSchema.Warnings.Text);

    if FSchema.Status = stCreate then
      CreateDatabasePhys;

    TioDBFactory.Script(FConnectionDefName, FScript.SQL).Execute;

    // Rebuilds schema and script to keep them consistent with the new situation
    RebuildSchema;
    RebuildScript;
  end;
end;

procedure TioDBBuilderEngine_New.CreateOrUpdateTable(const ATableName: String);
var
  LScript: IioDBBuilderSqlScript;
  LStrategy: IioDBBuilderStrategy;
  LTable: IioDBBuilderSchemaTable;
begin
  LScript := TioDBBuilderFactory.NewSqlScript;
  LTable := FSchema.FindTable(ATableName);
  LStrategy := TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, LScript);

  case LTable.Status of
    stUpdate:
      LStrategy.CreateTable(LTable);
    stCreate:
      LStrategy.AlterTable(LTable);
  end;

  TioDBFactory.Script(FConnectionDefName, LScript.SQL).Execute;

  // Rebuilds schema and script to keep them consistent with the new situation
  RebuildSchema;
  RebuildScript;
end;

function TioDBBuilderEngine_New.GetDBStatus: TioDBBuilderStatus;
begin
  Result := FSchema.Status;
end;

function TioDBBuilderEngine_New.GetSchema: IioDBBuilderSchema;
begin
  Result := FSchema;
end;

function TioDBBuilderEngine_New.GetScript: IioDBBuilderSqlScript;
begin
  Result := FScript;
end;

function TioDBBuilderEngine_New.GetTableStatus(const ATableName: String): TioDBBuilderStatus;
begin
  Result := FSchema.FindTable(ATableName).Status;
end;

function TioDBBuilderEngine_New.GetWarnings: TStrings;
begin
  Result := FSchema.Warnings;
end;

procedure TioDBBuilderEngine_New.RebuildSchema;
begin
  FSchema := TioDBBuilderFactory.NewSchema(FConnectionDefName, FBuildIndexes, FBuildForeignKeys);
  TioDBBuilderFactory.NewDBAnalyzer(FConnectionDefName, FSchema, FSqlGenerator, FForceToCreateNewDB).Analyze;
end;

procedure TioDBBuilderEngine_New.RebuildScript;
begin
  FScript := TioDBBuilderFactory.NewSqlScript;
  case FSchema.Status of
    stCreate:
      TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, FScript).GenerateCreateDatabaseScript;
    stUpdate:
      TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator, FScript).GenerateUpdateDatabaseScript;
  end;
end;

end.
