{
  ****************************************************************************
  *                                                                          *
  *           iORM - (interfaced ORM)                                        *
  *                                                                          *
  *           Copyright (C) 2015-2023 Maurizio Del Magno                     *
  *                                                                          *
  *           mauriziodm@levantesw.it                                        *
  *           mauriziodelmagno@gmail.com                                     *
  *           https://github.com/mauriziodm/iORM.git                         *
  *                                                                          *
  ****************************************************************************
  *                                                                          *
  * This file is part of iORM (Interfaced Object Relational Mapper).         *
  *                                                                          *
  * Licensed under the GNU Lesser General Public License, Version 3;         *
  *  you may not use this file except in compliance with the License.        *
  *                                                                          *
  * iORM is free software: you can redistribute it and/or modify             *
  * it under the terms of the GNU Lesser General Public License as published *
  * by the Free Software Foundation, either version 3 of the License, or     *
  * (at your option) any later version.                                      *
  *                                                                          *
  * iORM is distributed in the hope that it will be useful,                  *
  * but WITHOUT ANY WARRANTY; without even the implied warranty of           *
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            *
  * GNU Lesser General Public License for more details.                      *
  *                                                                          *
  * You should have received a copy of the GNU Lesser General Public License *
  * along with iORM.  If not, see <http://www.gnu.org/licenses/>.            *
  *                                                                          *
  ****************************************************************************
}
/// <summary>
/// Firebird-specific implementation of DBBuilder Strategy.
/// Inherits common ALTER TABLE logic from TioDBBuilderStrategyWithAlterTable
/// and provides Firebird-specific behavior through hook method overrides.
/// </summary>
unit iORM.DBBuilder.Strategy.Firebird;

interface

uses
  iORM.DBBuilder.Interfaces,
  iORM.DBBuilder.Strategy.WithAlterTable

  ;


type
  TioDBBuilderStrategyFirebird = class(TioDBBuilderStrategyWithAlterTable)
  protected
    // RDBMS-specific invalid type conversions
    function GetInvalidTypeConversions: string; override;
    // Hook overrides for Firebird-specific behavior
    procedure DoCheckKeyGenerationCompatibility; override;
    procedure DoGetNotNullChangeSupported(var AIsNotNullChangeSupported: Boolean); override;
    procedure DoGetBlobSubTypeChangePermitted(var AIsBlobSubTypeChangePermitted: Boolean); override;
  end;


implementation

uses
  System.SysUtils,
  iORM.CommonTypes

  ;


const
  INVALID_FIELDTYPE_CONVERSIONS =
    '[timestamp->decimal][timestamp->numeric][timestamp->integer][date->decimal][date->numeric]' +
    '[date->integer][time->numeric][time->decimal][time->integer][varchar->decimal][varchar->integer][varchar->date][varchar->time]' +
    '[varchar->datetime][char->decimal][char->integer][char->date][char->time][char->datetime]';


{ TioDBBuilderStrategyFirebird }

function TioDBBuilderStrategyFirebird.GetInvalidTypeConversions: string;
begin
  Result := INVALID_FIELDTYPE_CONVERSIONS;
end;

procedure TioDBBuilderStrategyFirebird.DoGetNotNullChangeSupported(var AIsNotNullChangeSupported: Boolean);
begin
  // Firebird: SET NOT NULL / DROP NOT NULL is only supported from Firebird 3.0+
  AIsNotNullChangeSupported := SqlGenerator.DBMSInfo.IsAtLeast(3, 0);
end;

procedure TioDBBuilderStrategyFirebird.DoGetBlobSubTypeChangePermitted(var AIsBlobSubTypeChangePermitted: Boolean);
begin
  // Firebird: BLOB subtype changes are NOT permitted
  AIsBlobSubTypeChangePermitted := False;
end;

procedure TioDBBuilderStrategyFirebird.DoCheckKeyGenerationCompatibility;
var
  LTable: IioDBBuilderSchemaTable;
begin
  // Check for Identity key generation on Firebird < 3.0
  // Identity columns (GENERATED BY DEFAULT AS IDENTITY) require Firebird 3.0+
  if not SqlGenerator.DBMSInfo.IsAtLeast(3, 0) then
    for LTable in Schema.Tables.Values do
      if LTable.UsesIdentityForKeyGeneration then
        Script.Warnings.Add(Format(
          'Table ''%s'' uses Identity key generation which requires Firebird 3.0+. ' +
          'Detected version: %s. Consider using [ioKeySequence] attribute or upgrade Firebird.',
          [LTable.Name, SqlGenerator.DBMSInfo.ToString]));
end;

end.
