{
  ****************************************************************************
  *                                                                          *
  *           iORM - (interfaced ORM)                                        *
  *                                                                          *
  *           Copyright (C) 2015-2023 Maurizio Del Magno                     *
  *                                                                          *
  *           mauriziodm@levantesw.it                                        *
  *           mauriziodelmagno@gmail.com                                     *
  *           https://github.com/mauriziodm/iORM.git                         *
  *                                                                          *
  ****************************************************************************
  *                                                                          *
  * This file is part of iORM (Interfaced Object Relational Mapper).         *
  *                                                                          *
  * Licensed under the GNU Lesser General Public License, Version 3;         *
  *  you may not use this file except in compliance with the License.        *
  *                                                                          *
  * iORM is free software: you can redistribute it and/or modify             *
  * it under the terms of the GNU Lesser General Public License as published *
  * by the Free Software Foundation, either version 3 of the License, or     *
  * (at your option) any later version.                                      *
  *                                                                          *
  * iORM is distributed in the hope that it will be useful,                  *
  * but WITHOUT ANY WARRANTY; without even the implied warranty of           *
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            *
  * GNU Lesser General Public License for more details.                      *
  *                                                                          *
  * You should have received a copy of the GNU Lesser General Public License *
  * along with iORM.  If not, see <http://www.gnu.org/licenses/>.            *
  *                                                                          *
  ****************************************************************************
}
unit iORM.DBBuilder.Engine;

interface

uses
  System.Classes,

  iORM.CommonTypes,
  iORM.Context.Table.Interfaces,
  iORM.DBBuilder.Interfaces,
  iORM.DBBuilder.SqlScript.Base

  ;

type

  TioDBBuilderEngine = class(TInterfacedObject, IioDBBuilderEngine)
  private
    FSchema: IioDBBuilderSchema;
    FSqlGenerator: IioDBBuilderSqlGenerator;
    FConnectionDefName: string;
    FSchemaAnalyzed: boolean;
    procedure CreateDatabase;
    function GetWarnings: TStrings;
    function GetSchema: IioDBBuilderSchema;
    function GetAnalyzed: boolean;
  protected
  public
    constructor Create(const AConnectionDefName: String; const AddIndexes, AddForeignKeys: Boolean);

    /// <summary>
    ///  Analyzes the schema generated by entities mapping and current database schema updating the schema status.
    ///  It must be called before CreateOrAlterDB, BuildCreateDBSqlScript, BuildUpdateDBSqlScript or BuildCreateOrAlterDBSqlScript methods.
    /// <param name="ForceCreate">Forces the analyzer to act if the database should be created</param>
    /// <remarks>
    ///  If the ForceCreate parameter is true, the analyzer behaves like the database doesn't exists and should be created even if it already exists.
    ///  If the ForceCreate parameter is false, the analyzer behaves like normal, acting as if the database doesn't exists if not exists or updated it if already exists.
    /// </remarks>
    /// </summary>
    function Analyze(const ForceCreate: boolean = False): TioDBBuilderStatus;
    /// <summary>
    ///  Build Creates or Alter database SQL script based on schema status.
    /// <param name="AScript">The script where sql instructions will be returned.</param>
    /// </summary>
    procedure BuildCreateOrUpdateDBSqlScript(const AScript: IioDBBuilderSqlScript);
    /// <summary>
    ///  Build Creates database SQL script regardless of schema status.
    /// <param name="AScript">The script where sql instructions will be returned.</param>
    /// </summary>
    procedure BuildCreateDBSqlScript(const AScript: IioDBBuilderSqlScript);
    /// <summary>
    ///  Build update database SQL script regardless of schema status.
    /// <param name="AScript">The script where sql instructions will be returned.</param>
    /// </summary>
    procedure BuildUpdateDBSqlScript(const AScript: IioDBBuilderSqlScript);
    /// <summary>
    ///  Creates or update the database depending on the actual schema/database status.
    ///  No need to call Analyze because it is called internally.
    /// <param name="Force">Forces the execution regardless of the schema status.</param>
    /// </summary>
    procedure CreateOrUpdateDB(const Force: Boolean = False; const AScript: IioDBBuilderSqlScript = nil); overload;
    /// <summary>
    ///  Creates or update the the table depending on the actual schema status.
    /// <param name="ATable">Schema of the table to be created/updated.</param>
    /// <param name="AddIndexes">Enable/Disable the creation table indexes.</param>
    /// <param name="AddForeignKeys">Enabled/Disable the creation of table foreign keys.</param>
    /// </summary>
    procedure CreateOrUpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes, AddForeignKeys: Boolean);
    /// <summary>
    ///  Creates the table using the schema passed.
    /// <param name="ATable">Schema of the table to be created/updated.</param>
    /// <param name="AddIndexes">Enable/Disable the creation table indexes.</param>
    /// <param name="AddForeignKeys">Enabled/Disable the creation of table foreign keys.</param>
    /// </summary>
    procedure CreateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes, AddForeignKeys: Boolean);
    /// <summary>
    ///  Updates the table using the schema passed.
    /// <param name="ATable">Schema of the table to be created/updated.</param>
    /// <param name="AddIndexes">Enable/Disable the creation table indexes.</param>
    /// <param name="AddForeignKeys">Enabled/Disable the creation of table foreign keys.</param>
    /// </summary>
    procedure UpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes, AddForeignKeys: Boolean);

    property Analyzed: boolean read GetAnalyzed;
    property Schema: IioDBBuilderSchema read GetSchema;
    property Warnings: TStrings read GetWarnings;
  end;

implementation

uses
  System.SysUtils,
  System.TypInfo,

  iORM.DBBuilder.QueryEngine,
  iORM.DBBuilder.Factory,
  iORM.DBBuilder.Schema,
  iORM.DB.Consts,
  iORM.DB.Factory,
  iORM.Exceptions

  ;

{ TioDBBuilderEngine }

function TioDBBuilderEngine.Analyze(const ForceCreate: boolean): TioDBBuilderStatus;
var
  LDBAnalyzer: IioDBBuilderDBAnalyzer;
begin
  LDBAnalyzer := TioDBBuilderFactory.NewDBAnalyzer(FConnectionDefName, FSchema, FSqlGenerator);
  LDBAnalyzer.Analyze(ForceCreate);

  Result := FSchema.Status;
end;

procedure TioDBBuilderEngine.BuildCreateDBSqlScript(const AScript: IioDBBuilderSqlScript);
begin
  if not Assigned(AScript) then
    raise EArgumentNilException.CreateFmt('%s.%s: %s', [ClassName, 'BuildCreateDBSqlScript', 'AScript is not assigned.']);

  if not Analyzed then
    raise EioGenericException.Create(ClassName, 'BuildCreateDBSqlScript', 'Unable to build SQL script: schema not analyzed');

  TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator).GenerateCreateDatabaseScript(AScript);
end;

procedure TioDBBuilderEngine.BuildCreateOrUpdateDBSqlScript(const AScript: IioDBBuilderSqlScript);
begin
  if not Analyzed then
    raise EioGenericException.Create(ClassName, 'BuildCreateDBSqlScript', 'Unable to build SQL script: schema not analyzed');

  if not Assigned(AScript) then
    raise EioArgumentNilException.Create(ClassName, 'BuildCreateOrUpdateDBSqlScript', 'AScript is not assigned.');

  case Schema.Status of
    stCreate: TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator).GenerateCreateDatabaseScript(AScript);
    stUpdate: TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator).GenerateUpdateDatabaseScript(AScript);
  else
    raise EioGenericException.Create(ClassName, 'BuildCreateOrUpdateDBSqlScript', 'Unable to build SQL script: schema not analyzed');
  end;
end;

procedure TioDBBuilderEngine.BuildUpdateDBSqlScript(const AScript: IioDBBuilderSqlScript);
begin
  if not Assigned(AScript) then
    raise EioArgumentNilException.Create(ClassName, 'BuildUpdateDBSqlScript', 'AScript is not assigned.');

  if not Analyzed then
    raise EioGenericException.Create(ClassName, 'BuildUpdateDBSqlScript', 'Unable to build SQL script: schema not analyzed');

  TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator).GenerateUpdateDatabaseScript(AScript);
end;

constructor TioDBBuilderEngine.Create(const AConnectionDefName: String; const AddIndexes, AddForeignKeys: Boolean);
begin
  FSchemaAnalyzed := False;
  FConnectionDefName := AConnectionDefName;
  FSchema := TioDBBuilderFactory.NewSchema(FConnectionDefName, AddIndexes, AddForeignKeys);
  FSqlGenerator := TioDBBuilderFactory.NewSqlGenerator(FConnectionDefName);
end;

procedure TioDBBuilderEngine.CreateDatabase;
var
  LStrategy: IioDBBuilderStrategy;
begin
  if not Analyzed then
    raise EioGenericException.Create(ClassName, 'CreateDatabase', 'Unable to create database: schema not analyzed');

  LStrategy := TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator);
  LStrategy.CreateDatabase;
end;

procedure TioDBBuilderEngine.CreateOrUpdateDB(const Force: Boolean; const AScript: IioDBBuilderSqlScript);
var
  LScript: IioDBBuilderSqlScript;
  LBuildScript: boolean;
  LStatus: TioDBBuilderStatus;
begin
  LBuildScript := not Assigned(AScript);

  // Carlo Marona (2025-10-15): Do not pass Force param of this method to Analyze method. They have different behavior
  if LBuildScript then
    LStatus := Analyze;

  if (LStatus > stClean) or Force then
  begin
    if Schema.WarningExists then
      raise EioGenericException.Create(ClassName, 'CreateOrUpdateDB',
        'Database must be updated but WARNINGS exists.' + sLineBreak +
        FSchema.Warnings.Text
      );

    if LBuildScript then
      LScript := TioDBBuilderFactory.NewSqlScript
    else
      LScript := AScript;

    if LStatus = stCreate then
    begin
      // Carlo Marona: create the database fisically, on the server or as a file depending on database type used
      CreateDatabase;

      if LBuildScript then
        BuildCreateDBSqlScript(LScript);
    end
    else if LStatus = stUpdate then
    begin
      if LBuildScript then
        BuildUpdateDBSqlScript(LScript);
    end;

    TioDBFactory.Script(FConnectionDefName, LScript.SQL).Execute;
  end;
end;

procedure TioDBBuilderEngine.CreateOrUpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes, AddForeignKeys: Boolean);
begin
  if not Assigned(ATable) then
    raise EioArgumentNilException.Create(ClassName, 'CreateOrUpdateTable', 'ATable is not assigned.');

  case ATable.Status of
    stCreate: CreateTable(ATable, AddIndexes, AddForeignKeys);
    stUpdate: UpdateTable(ATable, AddIndexes, AddForeignKeys);
  end;
end;

procedure TioDBBuilderEngine.CreateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes, AddForeignKeys: Boolean);
var
  LStrategy: IioDBBuilderStrategy;
  LScript: IioDBBuilderSqlScript;
begin
  if not Assigned(ATable) then
    raise EioArgumentNilException.Create(ClassName, 'CreateTable', 'ATable is not assigned.');

  if ATable.Status <> stCreate then
    exit;

  LScript := TioDBBuilderFactory.NewSqlScript;
  LStrategy := TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator);

  LStrategy.CreateTable(LScript, ATable);

  if AddIndexes then
    LStrategy.CreateTableIndexes(LScript, ATable);

  if AddForeignKeys then
    LStrategy.CreateTableForeignKeys(LScript, ATable);

  TioDBFactory.Script(FConnectionDefName, LScript.SQL).Execute;
end;

function TioDBBuilderEngine.GetAnalyzed: boolean;
begin
  Result := FSchemaAnalyzed;
end;

function TioDBBuilderEngine.GetSchema: IioDBBuilderSchema;
begin
  Result := FSchema;
end;

function TioDBBuilderEngine.GetWarnings: TStrings;
begin
  Result := FSchema.Warnings;
end;

procedure TioDBBuilderEngine.UpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes, AddForeignKeys: Boolean);
var
  LStrategy: IioDBBuilderStrategy;
  LScript: IioDBBuilderSqlScript;
begin
  if not Assigned(ATable) then
    raise EioArgumentNilException.Create(ClassName, 'UpdateTable', 'ATable is not assigned.');

  if ATable.Status <> stCreate then
    exit;

  LScript := TioDBBuilderFactory.NewSqlScript;
  LStrategy := TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator);

  LStrategy.AlterTable(LScript, ATable);

//  if AddIndexes then
//    LStrategy.CreateIndexes(LScript, ATable);
//
//  if AddForeignKeys then
//    LStrategy.CreateForeignKeys(LScript, ATable);

  TioDBFactory.Script(FConnectionDefName, LScript.SQL).Execute;
end;

end.
