{
  ****************************************************************************
  *                                                                          *
  *           iORM - (interfaced ORM)                                        *
  *                                                                          *
  *           Copyright (C) 2015-2023 Maurizio Del Magno                     *
  *                                                                          *
  *           mauriziodm@levantesw.it                                        *
  *           mauriziodelmagno@gmail.com                                     *
  *           https://github.com/mauriziodm/iORM.git                         *
  *                                                                          *
  ****************************************************************************
  *                                                                          *
  * This file is part of iORM (Interfaced Object Relational Mapper).         *
  *                                                                          *
  * Licensed under the GNU Lesser General Public License, Version 3;         *
  *  you may not use this file except in compliance with the License.        *
  *                                                                          *
  * iORM is free software: you can redistribute it and/or modify             *
  * it under the terms of the GNU Lesser General Public License as published *
  * by the Free Software Foundation, either version 3 of the License, or     *
  * (at your option) any later version.                                      *
  *                                                                          *
  * iORM is distributed in the hope that it will be useful,                  *
  * but WITHOUT ANY WARRANTY; without even the implied warranty of           *
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            *
  * GNU Lesser General Public License for more details.                      *
  *                                                                          *
  * You should have received a copy of the GNU Lesser General Public License *
  * along with iORM.  If not, see <http://www.gnu.org/licenses/>.            *
  *                                                                          *
  ****************************************************************************
}
unit iORM.DBBuilder.Engine;

interface

uses
  System.Classes,

  iORM.CommonTypes,
  iORM.Context.Table.Interfaces,
  iORM.DBBuilder.Interfaces,
  iORM.DBBuilder.Script

  ;

type

  TioDBBuilderEngine_New = class
  private
    FForeignKeysMode: TioDBBuilderIndexesAndFKMode;
    FIndexesMode: TioDBBuilderIndexesAndFKMode;
    FConnectionDefName: string;
    FSchema: IioDBBuilderSchema;
    FScript: IioDBBuilderSqlScript;
    FSqlGenerator: IioDBBuilderSqlGenerator;

    procedure CreateDatabasePhys;
    function GetDBStatus: TioDBBuilderStatus;
    function GetSchema: IioDBBuilderSchema;
    function GetScript: IioDBBuilderSqlScript;
    function GetTableStatus(const ATableName: String): TioDBBuilderStatus;
    function GetWarnings: TStrings;
  public
    constructor Create(const AConnectionDefName: String; const AIndexesMode, AForeignKeysMode: TioDBBuilderIndexesAndFKMode);

    procedure CreateOrUpdateDB(const AForce: Boolean = False);
    procedure CreateOrUpdateTable(const ATableName: String);
    procedure RebuildSchema;
    procedure RebuildScript;

    property DBStatus: TioDBBuilderStatus read GetDBStatus;
    property Schema: IioDBBuilderSchema read GetSchema;
    property Script: IioDBBuilderSqlScript read GetScript;
    property TableStatus[const TableName: String]: TioDBBuilderStatus read GetTableStatus;
    property Warnings: TStrings read GetWarnings;
  end;




  TioDBBuilderEngine = class(TInterfacedObject, IioDBBuilderEngine)
  private
    FAnalyzed: boolean;
    FConnectionDefName: string;
    FSchema: IioDBBuilderSchema;
    FSqlGenerator: IioDBBuilderSqlGenerator;
    procedure CreateDatabase;
    function GetWarnings: TStrings;
    function GetSchema: IioDBBuilderSchema;
    function GetAnalyzed: boolean;
  protected
  public
    constructor Create(const AConnectionDefName: String; const AIndexesMode, AForeignKeysMode: TioDBBuilderIndexesAndFKMode);

    /// <summary>
    ///  Analyzes the schema generated by entities mapping and current database schema updating the schema status.
    ///  It must be called before CreateOrAlterDB or BuildCreateOrUpdateDBSqlScript methods.
    ///  Not required by BuildCreateDBSqlScript, which builds a full create-from-scratch script without introspecting the DB.
    /// </summary>
    function Analyze: TioDBBuilderStatus;
    /// <summary>
    ///  Build Creates or Alter database SQL script based on schema status.
    /// <param name="AScript">The script where sql instructions will be returned.</param>
    /// </summary>
    procedure BuildCreateOrUpdateDBSqlScript(const AScript: IioDBBuilderSqlScript);
    /// <summary>
    ///  Builds a full "create from scratch" database SQL script regardless of the actual database
    ///  state, for documentation/baseline purposes. Does NOT require a prior Analyze call and does
    ///  not introspect the database schema: it works entirely off the schema built from the class
    ///  maps (the only DB touch is the lazy DBMSInfo version query needed for version-correct DDL).
    ///  The resulting script must NOT be executed against an existing database.
    /// <param name="AScript">The script where sql instructions will be returned.</param>
    /// </summary>
    procedure BuildCreateDBSqlScript(const AScript: IioDBBuilderSqlScript);
    /// <summary>
    ///  Creates or update the database depending on the actual schema/database status.
    ///  No need to call Analyze because it is called internally.
    /// <param name="Force">Forces the execution regardless of the schema status.</param>
    /// </summary>
    procedure CreateOrUpdateDB(const Force: Boolean = False; const AScript: IioDBBuilderSqlScript = nil); overload;
    /// <summary>
    ///  Creates or update the the table depending on the actual schema status.
    /// <param name="ATable">Schema of the table to be created/updated.</param>
    /// <param name="AddIndexes">Enable/Disable the creation table indexes.</param>
    /// <param name="AddForeignKeys">Enabled/Disable the creation of table foreign keys.</param>
    /// </summary>
    procedure CreateOrUpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean = True; const AddForeignKeys: Boolean = True);
    /// <summary>
    ///  Creates the table using the schema passed.
    /// <param name="ATable">Schema of the table to be created/updated.</param>
    /// <param name="AddIndexes">Enable/Disable the creation table indexes.</param>
    /// <param name="AddForeignKeys">Enabled/Disable the creation of table foreign keys.</param>
    /// </summary>
    procedure CreateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean = True; const AddForeignKeys: Boolean = True);
    /// <summary>
    ///  Updates the table using the schema passed.
    /// <param name="ATable">Schema of the table to be created/updated.</param>
    /// <param name="AddIndexes">Enable/Disable the creation table indexes.</param>
    /// <param name="AddForeignKeys">Enabled/Disable the creation of table foreign keys.</param>
    /// </summary>
    procedure UpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean = True; const AddForeignKeys: Boolean = True);

    property Analyzed: boolean read GetAnalyzed;
    property Schema: IioDBBuilderSchema read GetSchema;
    property Warnings: TStrings read GetWarnings;
  end;

implementation

uses
  System.SysUtils,
  System.TypInfo,

  iORM.DBBuilder.Factory,
  iORM.DBBuilder.Schema,
  iORM.DB.Consts,
  iORM.DB.Factory,
  iORM.Exceptions

  ;

{ TioDBBuilderEngine }

function TioDBBuilderEngine.Analyze: TioDBBuilderStatus;
var
  LDBAnalyzer: IioDBBuilderDBAnalyzer;
begin
  LDBAnalyzer := TioDBBuilderFactory.NewDBAnalyzer(FConnectionDefName, FSchema, FSqlGenerator);
  LDBAnalyzer.Analyze;
  FAnalyzed := True;

  Result := FSchema.Status;
end;

procedure TioDBBuilderEngine.BuildCreateDBSqlScript(const AScript: IioDBBuilderSqlScript);
begin
  if not Assigned(AScript) then
    raise EioInvalidArgumentException.Create(ClassName, 'BuildCreateDBSqlScript', 'AScript is not assigned.');

  // No Analyze needed: the schema is already fully populated from the class/entity maps in the
  // constructor (NewSchema -> BuildSchema, no DB access). GenerateScript_ForceCreate marks the whole
  // tree as stCreate, so any analyzed status would just be overwritten. The only residual DB touch is
  // the lazy DBMSInfo version query, required to emit version-correct DDL. This avoids the O(tables +
  // fields + indexes + FKs) catalog introspection that Analyze would otherwise perform pointlessly.
  TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator).GenerateScript_ForceCreate;
  AScript.Lines.Assign(FSchema.Script.Lines);
end;

procedure TioDBBuilderEngine.BuildCreateOrUpdateDBSqlScript(const AScript: IioDBBuilderSqlScript);
begin
  if not Assigned(AScript) then
    raise EioInvalidArgumentException.Create(ClassName, 'BuildCreateOrUpdateDBSqlScript', 'AScript is not assigned.');

  if not Analyzed then
    raise EioDBBuilderException.Create(ClassName, 'BuildCreateOrUpdateDBSqlScript', 'Unable to build SQL script: schema not analyzed');

  // Status-driven: the strategy generates a create or an update script according to the status
  // determined by the DBAnalyzer.
  TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator).GenerateScript_Sync;
  AScript.Lines.Assign(FSchema.Script.Lines);
end;

constructor TioDBBuilderEngine.Create(const AConnectionDefName: String; const AIndexesMode, AForeignKeysMode: TioDBBuilderIndexesAndFKMode);
begin
  FAnalyzed := False;
  FConnectionDefName := AConnectionDefName;
  // SqlGenerator must be created BEFORE Schema so that kgsAuto can be resolved
  FSqlGenerator := TioDBBuilderFactory.NewSqlGenerator(FConnectionDefName);
  FSchema := TioDBBuilderFactory.NewSchema(FConnectionDefName, AIndexesMode, AForeignKeysMode, FSqlGenerator);
end;

procedure TioDBBuilderEngine.CreateDatabase;
var
  LStrategy: IioDBBuilderStrategy;
begin
  if not Analyzed then
    raise EioDBBuilderException.Create(ClassName, 'CreateDatabase', 'Unable to create database: schema not analyzed');

  LStrategy := TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator);
  LStrategy.ScriptWrite_CreateDatabase;
end;

procedure TioDBBuilderEngine.CreateOrUpdateDB(const Force: Boolean; const AScript: IioDBBuilderSqlScript);
var
  LScript: IioDBBuilderSqlScript;
  LBuildScript: boolean;
  LStatus: TioDBBuilderStatus;
begin
  LBuildScript := not Assigned(AScript);

  if LBuildScript then
    LStatus := Analyze
  else
    LStatus := Schema.Status;

  if (LStatus > stClean) or Force then
  begin
    if FSchema.Script.Warnings.Lines.Count > 0 then
      raise EioDBBuilderException.Create(ClassName, 'CreateOrUpdateDB',
        'Database must be updated but WARNINGS exists.' + sLineBreak +
        FSchema.Script.Warnings.Lines.Text
      );

    if LBuildScript then
      LScript := TioDBBuilderFactory.NewSqlScript
    else
      LScript := AScript;

    // Physically create the database (on the server or as a file, depending on database type) only
    // when the analyzed status says it does not exist yet. This is a legitimate read of the status.
    if LStatus = stCreate then
      CreateDatabase; // Carlo Marona

    // Build the script status-driven (create or update according to the analyzed status).
    if LBuildScript then
      BuildCreateOrUpdateDBSqlScript(LScript);

    TioDBFactory.Script(FConnectionDefName, LScript.Lines).Execute;
  end;
end;

procedure TioDBBuilderEngine.CreateOrUpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean;
  const AddForeignKeys: Boolean);
begin
  if not Assigned(ATable) then
    raise EioInvalidArgumentException.Create(ClassName, 'CreateOrUpdateTable', 'ATable is not assigned.');

  case ATable.Status of
    stCreate: CreateTable(ATable, AddIndexes, AddForeignKeys);
    stUpdate: UpdateTable(ATable, AddIndexes, AddForeignKeys);
  end;
end;

procedure TioDBBuilderEngine.CreateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean;
  const AddForeignKeys: Boolean);
var
  LStrategy: IioDBBuilderStrategy;
begin
  if not Assigned(ATable) then
    raise EioInvalidArgumentException.Create(ClassName, 'CreateTable', 'ATable is not assigned.');

  if ATable.Status <> stCreate then
    exit;

  FSchema.Script.Clear;
  LStrategy := TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator);

  LStrategy.ScriptWrite_CreateTable(ATable);

  if AddForeignKeys then
    LStrategy.ScriptWrite_CreateTableForeignKeys(ATable);

  TioDBFactory.Script(FConnectionDefName, FSchema.Script.Lines).Execute;
end;

procedure TioDBBuilderEngine.UpdateTable(const ATable: IioDBBuilderSchemaTable; const AddIndexes: Boolean;
  const AddForeignKeys: Boolean);
var
  LStrategy: IioDBBuilderStrategy;
begin
  if not Assigned(ATable) then
    raise EioInvalidArgumentException.Create(ClassName, 'UpdateTable', 'ATable is not assigned.');

  if ATable.Status <> stCreate then
    exit;

  FSchema.Script.Clear;
  LStrategy := TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator);

  LStrategy.ScriptWrite_AlterTable(ATable);
  TioDBFactory.Script(FConnectionDefName, FSchema.Script.Lines).Execute;
end;

function TioDBBuilderEngine.GetAnalyzed: boolean;
begin
  Result := FAnalyzed;
end;

function TioDBBuilderEngine.GetSchema: IioDBBuilderSchema;
begin
  Result := FSchema;
end;

function TioDBBuilderEngine.GetWarnings: TStrings;
begin
  Result := FSchema.Script.Warnings.Lines;
end;

{ TioDBBuilderEngine_New }
constructor TioDBBuilderEngine_New.Create(const AConnectionDefName: String; const AIndexesMode, AForeignKeysMode: TioDBBuilderIndexesAndFKMode);
begin
  FForeignKeysMode := AForeignKeysMode;
  FIndexesMode := AIndexesMode;
  FConnectionDefName := AConnectionDefName;

  FSqlGenerator := TioDBBuilderFactory.NewSqlGenerator(AConnectionDefName);
  RebuildSchema;
  RebuildScript;
end;

procedure TioDBBuilderEngine_New.CreateDatabasePhys;
begin
  TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator).ScriptWrite_CreateDatabase;
end;

procedure TioDBBuilderEngine_New.CreateOrUpdateDB(const AForce: Boolean);
begin
  if (FSchema.Status > stClean) or AForce then
  begin
    if FSchema.Script.Warnings.Lines.Count > 0 then
      raise EioDBBuilderException.Create(ClassName, 'CreateOrUpdateDB', 'Database must be updated but WARNINGS exists.' + sLineBreak + FSchema.Script.Warnings.Lines.Text);

    if FSchema.Status = stCreate then
      CreateDatabasePhys;

    TioDBFactory.Script(FConnectionDefName, FScript.Lines).Execute;

    // Rebuilds schema and script to keep them consistent with the new situation
    RebuildSchema;
    RebuildScript;
  end;
end;

procedure TioDBBuilderEngine_New.CreateOrUpdateTable(const ATableName: String);
var
  LStrategy: IioDBBuilderStrategy;
  LTable: IioDBBuilderSchemaTable;
begin
  FSchema.Script.Clear;
  LTable := FSchema.FindTable(ATableName);
  LStrategy := TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator);

  case LTable.Status of
    stUpdate:
      LStrategy.ScriptWrite_CreateTable(LTable);
    stCreate:
      LStrategy.ScriptWrite_AlterTable(LTable);
  end;

  TioDBFactory.Script(FConnectionDefName, FSchema.Script.Lines).Execute;

  // Rebuilds schema and script to keep them consistent with the new situation
  RebuildSchema;
  RebuildScript;
end;

function TioDBBuilderEngine_New.GetDBStatus: TioDBBuilderStatus;
begin
  Result := FSchema.Status;
end;

function TioDBBuilderEngine_New.GetSchema: IioDBBuilderSchema;
begin
  Result := FSchema;
end;

function TioDBBuilderEngine_New.GetScript: IioDBBuilderSqlScript;
begin
  Result := FScript;
end;

function TioDBBuilderEngine_New.GetTableStatus(const ATableName: String): TioDBBuilderStatus;
begin
  Result := FSchema.FindTable(ATableName).Status;
end;

function TioDBBuilderEngine_New.GetWarnings: TStrings;
begin
  Result := FSchema.Script.Warnings.Lines;
end;

procedure TioDBBuilderEngine_New.RebuildSchema;
begin
  FSchema := TioDBBuilderFactory.NewSchema(FConnectionDefName, FIndexesMode, FForeignKeysMode, FSqlGenerator);
  TioDBBuilderFactory.NewDBAnalyzer(FConnectionDefName, FSchema, FSqlGenerator).Analyze;
end;

procedure TioDBBuilderEngine_New.RebuildScript;
begin
  FSchema.Script.Clear;
  // Status-driven: create or update script according to the status determined by the DBAnalyzer.
  TioDBBuilderFactory.NewStrategy(FConnectionDefName, FSchema, FSqlGenerator).GenerateScript_Sync;
  FScript := FSchema.Script;
end;

end.
